import assert from 'node:assert/strict';
import { canonicalJson, sha256Text } from '@kubeclaw/plugin-sdk';
import {buildRequest,parseCaseStudy,validateBundle} from '../src/protocol.ts';
const execution={runId:'run:executor',stageId:'report',attemptId:'attempt:contract',attemptNumber:2};
const artifact={artifactId:'source',namespace:'kubeclaw.implementation-agent',mediaType:'application/json',digest:sha256Text('{}'),sizeBytes:2,producer:execution};
const source={runId:'run:fixture',journalHead:sha256Text('journal fixture'),snapshotDigest:sha256Text('snapshot fixture'),sourceStageId:'source',sourceRevision:'a'.repeat(40),artifacts:[artifact]};
const {artifacts,...target}=source;
const unsigned={schemaVersion:'report-source-bundle.v1',target,pipelineId:'fixture',evidence:[{evidenceId:sha256Text(canonicalJson(artifact)),artifact}],facts:[]};
const bundle={...unsigned,digest:sha256Text(canonicalJson(unsigned))};
const input={task:'Protocol contract test; no run authority asserted.',source};
assert.equal(buildRequest('agent',input,execution,bundle).protocol,'kubeclaw.case-study.v4');
validateBundle(bundle,source);
assert.throws(()=>validateBundle({...bundle,pipelineId:'changed'},source));
const ids=bundle.evidence.map(item=>item.evidenceId);
const markdown=['Context','Challenge','Approach','Implementation','Verification','Outcome'].map(section=>`## ${section}\n\nDraft.`).join('\n\n');
const valid={status:'generated',markdown:`${markdown}\n\n[evidence:${ids[0]}]`,evidenceIds:ids};
const parsed=parseCaseStudy(valid,input,execution,bundle);
assert.deepEqual(parsed.execution,execution); assert.deepEqual(parsed.sourceBundle,bundle);
assert.equal(parsed.narrativeStatus,'draft-not-entailment-verified');
for(const bad of [{...valid,identity:{runId:'foreign'}},{...valid,extra:true}]) assert.throws(()=>parseCaseStudy(bad,input,execution,bundle));
assert.throws(()=>parseCaseStudy({...valid,evidenceIds:['foreign']},input,execution,bundle));
assert.throws(()=>parseCaseStudy({...valid,markdown:markdown.replace('## Challenge','## Context')},input,execution,bundle));
console.log(JSON.stringify({ok:true,plugin:'kubeclaw.case-study',suite:'protocol'}));
