import assert from 'node:assert/strict'; import crypto from 'node:crypto'; import { execFileSync } from 'node:child_process'; import fs from 'node:fs'; import http from 'node:http'; import os from 'node:os'; import path from 'node:path'; import { fileURLToPath } from 'node:url';
import { buildRegistry, createProductionNovaTestGate, discoverPackages, resolveTestPlan } from '@kubeclaw/nova-core';
import { BrowserPlaywrightCapabilityInvoker, BusterRemotePlanRuntime, BusterRemotePlanService, FileBusterPlanJobStore } from '@kubeclaw/buster-engine';
const sourceRoot=path.resolve('.'); const root=fs.mkdtempSync(path.join(os.tmpdir(),'e2e-remote-vertical-')); const repository=path.join(root,'repository'); const token='e2e-remote-vertical-token-00000001'; const keys=crypto.generateKeyPairSync('ed25519'); const privateKey=keys.privateKey.export({type:'pkcs8',format:'pem'}); const publicKey=keys.publicKey.export({type:'spki',format:'pem'});
const server=http.createServer((_request,response)=>{response.setHeader('content-type','text/html');response.end('<!doctype html><html><body><h1>E2E ready</h1></body></html>');});
try { fs.cpSync('skills/buster/plugins/playwright/tests/fixture',repository,{recursive:true}); await new Promise<void>((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);}); const address=server.address();if(!address||typeof address==='string')throw new Error('E2E_BIND_FAILED');const origin=`http://127.0.0.1:${address.port}`;
  execFileSync('git',['-C',repository,'init','-q']);execFileSync('git',['-C',repository,'config','user.email','e2e@example.invalid']);execFileSync('git',['-C',repository,'config','user.name','E2E Proof']);execFileSync('git',['-C',repository,'add','.']);execFileSync('git',['-C',repository,'commit','-qm','E2E fixture']);
  const pluginRoot=path.resolve('skills/buster/plugins');const registry=buildRegistry(discoverPackages({installationRoots:[pluginRoot],trustPolicy:{trustedBuiltinRoots:[pluginRoot],allowedSourceDigests:new Map(),verifiedAttestations:new Map(),verifierId:'e2e-remote'}}));const limits={cpuMillis:120000,memoryBytes:4294967296,logBytes:4194304,artifactBytes:67108864,artifactFiles:32,processes:64};
  const plan=resolveTestPlan({planId:'plan:e2e:remote',runId:'run:e2e:remote',project:'e2e-remote',scope:{moduleId:'e2e',gateId:null},createdAt:'2026-09-04T00:00:00.000Z',declaration:{tests:{playwright:{uses:'kubeclaw.playwright@1',mode:'blocking',retries:0,concurrencyGroup:'browser-playwright',config:{url:origin,projectDirectory:'.',configFile:'playwright.config.ts',workers:1,timeoutMs:60000}}},concurrencyLimits:{'browser-playwright':1}},suiteTemplates:[],registry,facts:{changedPaths:['specs/home.spec.ts'],moduleType:'service',pipelineStage:'test'},policy:{defaultTimeoutMs:90000,maximumTimeoutMs:90000,defaultLimits:limits,maximumLimits:limits,maximumRetryCount:1,maximumMatrixSize:1,maximumNodes:2,defaultConcurrencyLimit:1,maximumConcurrencyLimits:{'browser-playwright':1}}});
  const records={maximumRecords:100,maximumBytes:134217728,maximumRecordBytes:67108864};const store=new FileBusterPlanJobStore(path.join(root,'buster-state'),{recordLimits:records,maximumArchiveBytes:8388608,maximumResultBytes:67108864,maximumResultStoreBytes:134217728,trustedSourceAuthority:'nova:production',sourceAttestationPublicKey:publicKey});
  const service=new BusterRemotePlanService({store,registry,workerRevision:'b'.repeat(40),runtimeRoot:path.join(root,'buster-runs'),tarExecutable:'/usr/bin/tar',maximumExtractedBytes:33554432,allowedCapabilities:new Set(['browser.playwright']),browserPlaywright:{allowedOrigins:[origin],allowedTargetPorts:[address.port],playwrightExecutable:path.join(sourceRoot,'node_modules/.bin/playwright'),sandboxExecutable:fileURLToPath(import.meta.resolve('@kubeclaw/plugin-foundation/isolation/plugin-sandbox')),runtimeNodeModules:path.join(sourceRoot,'node_modules'),browsersPath:'/ms-playwright',readOnlyRoots:['/app','/ms-playwright','/usr','/lib','/lib64','/etc/fonts','/etc/hosts','/etc/nsswitch.conf','/etc/resolv.conf','/etc/ssl','/proc','/sys','/dev'],maximumWorkers:2,maximumExecutionMs:120000,maximumOutputBytes:4194304,maximumResultBytes:67108864,maximumArtifactBytes:67108864,maximumArtifactFiles:32,maximumProcesses:64,maximumMemoryBytes:4294967296,maximumCpuMillis:120000,terminationGraceMs:5000,allowSampledResourceLimits:true}});
  const runtime=new BusterRemotePlanRuntime({service,host:'127.0.0.1',port:0,token,maximumRequestBytes:16777216,maximumResponseBytes:65536,maximumResultBytes:67108864,shutdownTimeoutMs:5000});const runtimeAddress=await runtime.start();try{const gate=createProductionNovaTestGate({stateRoot:path.join(root,'nova-state'),endpoint:`http://127.0.0.1:${runtimeAddress.port}`,token,sourceAuthority:'nova:production',sourceAttestationPrivateKey:privateKey,pollMilliseconds:10,maximumResponseBytes:65536,maximumResultBytes:67108864,maximumArchiveBytes:8388608,maximumArchiveStoreBytes:33554432,maximumEvidenceBytes:67108864,maximumEvidenceStoreBytes:134217728,recordLimits:records,legacyLedger:{}});const gateRequest={idempotencyKey:'e2e:remote:vertical',pipelineStageId:'stage:e2e',plan,repositoryRoot:repository,repositoryId:'repository:e2e',maximumConcurrency:1,grants:new Map([['playwright',['browser.playwright']]]),submittedAt:'2026-09-04T00:00:00.000Z',timeoutMs:180000,legacySuites:[]};const executed=await gate.execute(gateRequest);assert.equal(executed.remote.status.state,'completed');const reference=executed.remote.status.result!;const result=JSON.parse((await service.result(executed.remote.status.jobId,reference.contentDigest,reference.sizeBytes)).toString('utf8'));assert.equal(executed.remote.decision.state,'passed',JSON.stringify(result));assert.equal(result.attempts[0].providerDetails.values.browserProjects.includes('real-chromium'),true);assert.equal(result.attempts[0].providerDetails.values.resourceEnforcement,'sampled');assert.equal(result.attempts[0].evidence.some((item:any)=>item.type==='test-report'),true);const duplicate=await gate.execute(gateRequest);assert.equal(duplicate.remote.status.jobId,executed.remote.status.jobId);assert.equal(duplicate.remote.decision.decisionDigest,executed.remote.decision.decisionDigest);const imports=JSON.parse(fs.readFileSync(path.join(root,'nova-state/imports/records/store.json'),'utf8')).records;assert.equal(imports.some((record:any)=>record.payload?.decision?.decisionDigest===executed.remote.decision.decisionDigest),true);}finally{await runtime.stop();}
} finally { await new Promise<void>((resolve)=>server.close(()=>resolve())); fs.rmSync(root,{recursive:true,force:true}); }
console.log(JSON.stringify({ok:true,phase:'e2e-remote-vertical',scenarios:['exact-origin','authenticated-dispatch','durable-result','duplicate-delivery','evidence-import','nova-gate-decision'],authenticatedDispatch:true,evidenceImported:true,realChromium:true,mocks:0,wrappers:0}));
