import assert from 'node:assert/strict';import fs from 'node:fs';
const inventory=JSON.parse(fs.readFileSync('docs/architecture/pipeline-test-gate-security-cutover-inventory.json','utf8'));for(const file of inventory.legacyFilesToDelete)assert.equal(fs.existsSync(file),false,`legacy file remains: ${file}`);for(const file of inventory.replacementFilesRequired)assert.equal(fs.existsSync(file),true,`replacement missing: ${file}`);for(const check of inventory.requiredAbsence)if(fs.existsSync(check.file))assert.equal(fs.readFileSync(check.file,'utf8').includes(check.token),false,`legacy token remains: ${check.file}`);
assert.equal(fs.existsSync('contracts/pipeline-test-gate/v1/legacy-suite-bridge.json'),false);const status=JSON.parse(fs.readFileSync('docs/architecture/pipeline-test-gate-suite-migration-status.json','utf8')).suites.find((item:any)=>item.id==='security');assert.equal(status.sourceCutover,'complete');assert.equal(status.productionAcceptance,'pending');
const scaffold=fs.readFileSync('skills/nova/project_setup/tools/progress-scaffold-discovery.ts','utf8');assert.match(scaffold,/LEGACY_SECURITY_CONFIGURATION_RETIRED/u);const workspace=fs.readFileSync('tests/verification/e2e/real-run-workspace.mjs','utf8');for(const provider of ['security-headers','dependency-scan-trivy','image-scan-trivy','kubernetes-policy-security','kubernetes-runtime-security'])assert.match(workspace,new RegExp(`kubeclaw\\.${provider}@1`));
assert.match(scaffold, /!hasDependencySecurity[\s\S]*kubeclaw\.dependency-scan-trivy@1/u,
  'project setup must add the sole dependency scanner to each Buster scope');
const production = fs.readFileSync('tests/verification/e2e/run-v2-production-pipeline.mts', 'utf8');
assert.match(production, /REAL_E2E_MANDATORY_DEPENDENCY_SECURITY_MISSING/u,
  'production must reject a provider plan without the sole dependency scanner');
const role=JSON.parse(fs.readFileSync('packaging/runtime/roles/buster.json','utf8'));assert.equal(role.plugins.includes('kubeclaw.security-providers'),true);const docker=fs.readFileSync('docker/Dockerfile.buster-runtime','utf8');assert.match(docker,/TRIVY_VERSION=0\.74\.0/u);const entrypoint=fs.readFileSync('docker/buster-runtime-entrypoint.sh','utf8');assert.match(entrypoint,/'security\.scan'/u);assert.match(entrypoint,/'kubernetes\.runtime-security'/u);
assert.equal(role.plugins.includes('kubeclaw.buster-suite-runtime'),false);assert.doesNotMatch(entrypoint,/test\.suite\.execute|18892|BUSTER_LEGACY/u);assert.doesNotMatch(fs.readFileSync('my-values/nova-values.yaml','utf8'),/test\.suite\.execute|buster-suite-v2|18892/u);assert.doesNotMatch(fs.readFileSync('my-values/buster-values.yaml','utf8'),/buster-legacy|18892/u);assert.equal(fs.existsSync('skills/buster/plugins/buster-suite-runtime'),false);
const lintDependencies=fs.readFileSync('skills/nova/plugins/lint/src/engine/tool-registry-dependency-tools.ts','utf8');assert.doesNotMatch(lintDependencies,/id:\s*['"](?:npm-audit|pip-audit)['"]/u);
console.log(JSON.stringify({ok:true,phase:'security-cutover',authority:'provider-plan-only',productionAcceptance:'pending'}));
