import assert from 'node:assert/strict';
import fs from 'node:fs';
const inventory = JSON.parse(fs.readFileSync('docs/architecture/pipeline-test-gate-api-cutover-inventory.json', 'utf8'));
for (const file of inventory.legacyFilesToDelete) assert.equal(fs.existsSync(file), false, `legacy API file remains: ${file}`);
for (const file of inventory.replacementFilesRequired) assert.equal(fs.existsSync(file), true, `replacement missing: ${file}`);
const bridge = JSON.parse(fs.readFileSync('contracts/pipeline-test-gate/v1/legacy-suite-bridge.json', 'utf8'));
assert.equal(bridge.suites.api.state, 'migrated'); assert.equal(bridge.suites.api.successor, 'kubeclaw.api-suite@1');
const protocol = fs.readFileSync('skills/buster/plugins/buster-suite-runtime/src/protocol.ts', 'utf8');
assert.doesNotMatch(protocol, /'api'/u);
const runner = fs.readFileSync('skills/buster/plugins/buster-suite-runtime/src/runtime/runners/suite-runner.ts', 'utf8');
assert.doesNotMatch(runner, /\bapi\b/u);
const production = fs.readFileSync('tests/verification/e2e/run-v2-production-pipeline.mts', 'utf8');
assert.doesNotMatch(production, /'api'/u);
const scaffold = fs.readFileSync('skills/nova/project_setup/tools/progress-scaffold-discovery.ts', 'utf8');
assert.match(scaffold, /uses: 'kubeclaw\.api-flow@1'/u);
assert.match(scaffold, /LEGACY_API_SPEC_VERSION_RETIRED/u);
const realWorkspace = fs.readFileSync('tests/verification/e2e/real-run-workspace.mjs', 'utf8');
assert.match(realWorkspace, /'api-flow': \{ uses: 'kubeclaw\.api-flow@1'/u);
assert.match(realWorkspace, /openapi: \{ uses: 'kubeclaw\.openapi@1'/u);
assert.match(realWorkspace, /inputs: deploymentInput/u);
const runtimeEntrypoint = fs.readFileSync('docker/buster-runtime-entrypoint.sh', 'utf8');
assert.match(runtimeEntrypoint, /BUSTER_NETWORK_HTTP_ALLOW_WEBSOCKET:-false/u);
assert.match(runtimeEntrypoint, /allowWebSocket: process\.env\.BUSTER_NETWORK_HTTP_ALLOW_WEBSOCKET === 'true'/u);
const deploy = fs.readFileSync('scripts/deploy.sh', 'utf8');
assert.match(deploy, /cmd_nova_api_preflight/u);
assert.match(deploy, /nova-api-production-preflight\.mts/u);
assert.match(deploy, /cmd_nova_api_preflight nova-api-preflight "\$immutable_image"/u);
assert.match(deploy, /const orchestrated = \['a11y', 'api', 'build'/u);
const status = JSON.parse(fs.readFileSync('docs/architecture/pipeline-test-gate-suite-migration-status.json', 'utf8'));
const apiStatus = status.suites.find((suite: any) => suite.id === 'api');
assert.equal(apiStatus.sourceCutover, 'complete');
assert.equal(apiStatus.productionAcceptance, 'pending');
console.log(JSON.stringify({ ok: true, phase: 'api-cutover', authority: 'provider-plan-only', legacyFiles: inventory.legacyFilesToDelete.length }));
