import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {checkPipelineObservabilityContract,contentDigest,decodePipelineObservabilityContract,producerClosureDigest,producerRecordDigest} from '../../../contracts/pipeline-observability/v1/src/index.ts';

const fixturePath='contracts/pipeline-observability/v1/fixtures/producer-record.json';
const record=JSON.parse(fs.readFileSync(fixturePath,'utf8'));
assert.equal(record.recordDigest,producerRecordDigest(record));
assert.equal(checkPipelineObservabilityContract('producerRecord',record).ok,true);
assert.equal(checkPipelineObservabilityContract('producerRecord',{...record,extra:true}).ok,false);
assert.equal(checkPipelineObservabilityContract('producerRecord',{...record,recordType:'attempt.completed'}).ok,false);
assert.equal(checkPipelineObservabilityContract('producerRecord',{...record,recordDigest:`sha256:${'0'.repeat(64)}`}).ok,false);
const {moduleId:_,...incompleteCorrelation}=record.correlation;
assert.equal(checkPipelineObservabilityContract('producerRecord',{...record,correlation:incompleteCorrelation}).ok,false);
assert.equal(checkPipelineObservabilityContract('producerRecord',{...record,sequence:Number.MAX_SAFE_INTEGER+1}).ok,false);
const producer=record.producer;
const replay={schemaVersion:'replay-range.v1',producer,pipelineRunId:'run:1',fromSequence:2,toSequence:4,requestedAt:'2026-08-09T12:01:00Z'};
assert.equal(checkPipelineObservabilityContract('replayRange',replay).ok,true);
assert.equal(checkPipelineObservabilityContract('replayRange',{...replay,toSequence:1}).ok,false);
const closureBase={schemaVersion:'producer-closure.v1' as const,closureId:'closure:worker:1',producer,pipelineRunId:'run:1',firstSequence:1,finalSequence:1,recordCount:1,requiredEvidenceIds:[],closedAt:'2026-08-09T12:02:00Z'};
const closure={...closureBase,closureDigest:producerClosureDigest(closureBase)};
assert.equal(checkPipelineObservabilityContract('producerClosure',closure).ok,true);
assert.equal(checkPipelineObservabilityContract('producerClosure',{...closure,recordCount:2}).ok,false);
const shiftedClosureBase={...closureBase,firstSequence:2,finalSequence:2,recordCount:1};
assert.equal(checkPipelineObservabilityContract('producerClosure',{...shiftedClosureBase,closureDigest:producerClosureDigest(shiftedClosureBase)}).ok,false);
const complete={schemaVersion:'observability-completeness.v1',pipelineRunId:'run:1',state:'complete',requiredClosureIds:['closure:worker:1'],admittedClosureIds:['closure:worker:1'],missingClosureIds:[],missingRanges:[],unresolvedItems:[],evaluatedAt:'2026-08-09T12:03:00Z'};
assert.equal(checkPipelineObservabilityContract('observabilityCompleteness',complete).ok,true);
const unresolved={itemId:'gap:evidence:1',kind:'missing-evidence',producer,subjectId:'evidence:1',reasonCode:'evidence-upload-failed'};
assert.equal(checkPipelineObservabilityContract('observabilityCompleteness',{...complete,unresolvedItems:[unresolved]}).ok,false);
assert.equal(checkPipelineObservabilityContract('observabilityCompleteness',{...complete,missingClosureIds:['closure:worker:1']}).ok,false);
assert.equal(checkPipelineObservabilityContract('producerRecord',{...record,occurredAt:'2026-08-09t12:00:00Z'}).ok,false);
assert.deepEqual(decodePipelineObservabilityContract('producerRecord',JSON.stringify(JSON.parse(fs.readFileSync(fixturePath,'utf8')))),record);
assert.throws(()=>decodePipelineObservabilityContract('producerRecord',JSON.stringify(record).replace('"sequence":1','"sequence":1.0')));
assert.throws(()=>decodePipelineObservabilityContract('producerRecord',`${JSON.stringify(record)}\n`));
assert.throws(()=>decodePipelineObservabilityContract('producerRecord',new Uint8Array([0xef,0xbb,0xbf,...new TextEncoder().encode(JSON.stringify(record))])));
const missingClosureItem={itemId:'gap:closure:1',kind:'missing-closure',producer,subjectId:'closure:worker:1',reasonCode:'producer-still-running'};
assert.equal(checkPipelineObservabilityContract('observabilityCompleteness',{...complete,state:'partial',admittedClosureIds:[],missingClosureIds:['closure:worker:1'],unresolvedItems:[missingClosureItem]}).ok,true);
assert.equal(checkPipelineObservabilityContract('observabilityCompleteness',{...complete,state:'partial'}).ok,false);
assert.equal(checkPipelineObservabilityContract('observabilityCompleteness',{...complete,state:'unknown'}).ok,false);
const reversedGap={schemaVersion:'producer-gap-report.v1',producer,pipelineRunId:'run:1',fromSequence:2,toSequence:1,state:'missing',reportedAt:'2026-08-09T12:04:00Z',reasonCode:'delivery-gap'};
assert.equal(checkPipelineObservabilityContract('observabilityCompleteness',{...complete,state:'partial',missingRanges:[reversedGap]}).ok,false);
assert.equal(contentDigest({z:'<script>',a:['é',1e-7,333333333.33333329]}),'sha256:f0491cd3e66eae1072cba2dcde39563e5c53ad8c33247bfd1ef9b06d693a4d04');
const go='/usr/local/go/bin/go';
const goCache=fs.mkdtempSync(path.join(os.tmpdir(),'kubeclaw-go-cache-'));
const goPath=fs.mkdtempSync(path.join(os.tmpdir(),'kubeclaw-go-path-'));
const goEnvironment={...process.env,GOCACHE:goCache,GOPATH:goPath,GOMODCACHE:path.join(goPath,'pkg','mod')};
try {
  execFileSync(go,['run','./fixturecheck',`../fixtures/producer-record.json`,`../fixtures/producer-closure.json`],{cwd:'contracts/pipeline-observability/v1/go',stdio:'pipe',env:goEnvironment});
} finally { execFileSync(go,['clean','-modcache'],{cwd:'contracts/pipeline-observability/v1/go',stdio:'pipe',env:goEnvironment});fs.rmSync(goCache,{recursive:true,force:true});fs.rmSync(goPath,{recursive:true,force:true}); }
console.log(JSON.stringify({ok:true,phase:'5.7-B',definitions:7,crossLanguageFixture:true}));
