import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {canonicalJson,producerRecordDigest} from '../../../contracts/pipeline-observability/v1/src/index.ts';
import {deliverPending,FileObservabilityAdmissionStore,FileProducerOutbox} from '../../../skills/common/plugin-runtime/foundation/observability/durable-delivery.ts';

const root=fs.mkdtempSync(path.join(os.tmpdir(),'kubeclaw-observability-delivery-'));
try{
  const outboxDirectory=path.join(root,'outbox');const admissionDirectory=path.join(root,'admission');
  let outbox=new FileProducerOutbox(outboxDirectory,{maximumRecords:3,maximumBytes:100000});
  const base={schemaVersion:'producer-record.v1' as const,recordId:'record:1',producer:{producerId:'worker:1',bootId:'boot:1',producerType:'buster'},sequence:1,recordType:'attempt.started',occurredAt:'2026-08-09T12:00:00Z',correlation:{pipelineRunId:'run:1',moduleId:'api',gateId:'final',attemptId:'attempt:1',claimId:'claim:1',claimGeneration:1,traceId:'trace:1',parentEventId:null},payload:{state:'started'}};
  const record=await outbox.append(base);
  outbox=new FileProducerOutbox(outboxDirectory,{maximumRecords:3,maximumBytes:100000});
  assert.equal((await outbox.pending()).length,1,'record must survive producer restart');
  const admissionLimits={maximumIngressBytes:10000,maximumRecords:10,maximumBytes:100000,maximumQuarantineRecords:1,maximumQuarantineBytes:10000};
  const admission=new FileObservabilityAdmissionStore(admissionDirectory,admissionLimits);
  const pendingBeforeLoss=await outbox.pending();
  await admission.admit(pendingBeforeLoss[0]!.bytes);
  await assert.rejects(()=>outbox.acknowledge({schemaVersion:'admission-acknowledgement.v1',recordId:record.recordId,producer:record.producer,pipelineRunId:'run:1',sequence:1,state:'admitted',admittedAt:'2026-08-09T12:00:01Z',canonicalCursor:0,recordDigest:record.recordDigest}),/OBSERVABILITY_CONTRACT_INVALID/);
  assert.equal((await outbox.pending()).length,1,'unacknowledged record must stay in outbox');
  const restartedAdmission=new FileObservabilityAdmissionStore(admissionDirectory,admissionLimits);
  assert.equal(await deliverPending(outbox,restartedAdmission),1,'replay must acknowledge the durable duplicate');
  assert.equal((await outbox.pending()).length,0);
  assert.equal((await restartedAdmission.snapshot()).entries.length,1,'replay must not duplicate admitted facts');
  assert.equal(await outbox.compact(),1,'only acknowledged records are compacted');
  await assert.rejects(()=>restartedAdmission.admit(`${canonicalJson(record)}\n`));
  const snapshot=await restartedAdmission.snapshot();
  assert.equal(snapshot.quarantine.length,1,'invalid raw bytes must be quarantined');
  await assert.rejects(()=>restartedAdmission.admit(`${canonicalJson(record)}  `));
  assert.equal((await restartedAdmission.snapshot()).quarantineOverflow?.count,1,'quarantine overflow must remain explicit and bounded');
  assert.equal((await restartedAdmission.observabilityIssues('run:1')).unresolvedItems.length,2,'quarantine and attributed overflow must remain visible to their run');
  assert.equal((await restartedAdmission.observabilityIssues('run:2')).unresolvedItems.length,0,'one run quarantine overflow must not degrade another run');
  const anotherRun={...record,recordId:'record:run:2',correlation:{...record.correlation,pipelineRunId:'run:2'}};
  await assert.rejects(()=>restartedAdmission.admit(`${canonicalJson(anotherRun)}  `),/OBSERVABILITY_ADMISSION_FULL/,'capacity exhaustion must fail instead of losing another run attribution');
  const malformedProducer=canonicalJson({...record,recordId:'record:run:3',producer:{...record.producer,unexpected:'field'},correlation:{...record.correlation,pipelineRunId:'run:3'}});
  await assert.rejects(()=>restartedAdmission.admit(malformedProducer),/OBSERVABILITY_ADMISSION_FULL/,'malformed but identifiable records must keep run attribution or fail admission');
  await assert.rejects(()=>restartedAdmission.admit('x'.repeat(10001)),/OBSERVABILITY_INGRESS_TOO_LARGE/);
  assert.equal((await restartedAdmission.snapshot()).quarantineOverflow?.count,2,'oversized ingress must leave bounded overflow metadata');
  const limited=new FileProducerOutbox(path.join(root,'limited'),{maximumRecords:1,maximumBytes:100000});
  await limited.append(base);
  await assert.rejects(()=>limited.append({...base,recordId:'record:2',sequence:2}),/OBSERVABILITY_OUTBOX_FULL/);
  assert.throws(()=>new FileProducerOutbox(path.join(root,'invalid-limit'),{maximumRecords:Number.POSITIVE_INFINITY,maximumBytes:1}),/OBSERVABILITY_OUTBOX_LIMIT_INVALID/);
  const outsideStore=path.join(root,'outside-store');fs.mkdirSync(outsideStore);const linkedStore=path.join(root,'linked-store');fs.symlinkSync(outsideStore,linkedStore);
  await assert.rejects(()=>new FileProducerOutbox(path.join(linkedStore,'outbox'),{maximumRecords:1,maximumBytes:10000}).append(base),/OBSERVABILITY_STORE_PATH_SYMLINK/,'durable stores must not follow a symlinked path component');
  const ordered=new FileProducerOutbox(path.join(root,'ordered'),{maximumRecords:3,maximumBytes:100000});
  const sequenceTwo=await ordered.append({...base,recordId:'record:2',sequence:2});await ordered.append(base);
  assert.deepEqual((await ordered.pending()).map((entry)=>entry.record.sequence),[1,2]);
  const concurrentDirectory=path.join(root,'concurrent');
  const concurrentA=new FileObservabilityAdmissionStore(concurrentDirectory,admissionLimits);const concurrentB=new FileObservabilityAdmissionStore(concurrentDirectory,admissionLimits);
  const recordTwo=await ordered.append({...base,recordId:'record:3',sequence:3});
  const [first,second]=await Promise.all([concurrentA.admit(canonicalJson(record)),concurrentB.admit(canonicalJson(recordTwo))]);
  assert.notEqual(first.acknowledgement.canonicalCursor,second.acknowledgement.canonicalCursor,'concurrent instances must not reuse a cursor');
  assert.equal((await concurrentA.snapshot()).entries.length,2,'concurrent admissions must not overwrite each other');
  const replayAfterRestart=await concurrentB.admit(canonicalJson(record));
  assert.equal(replayAfterRestart.acknowledgement.canonicalCursor,first.acknowledgement.canonicalCursor,'retained admission must preserve duplicate cursor');
  assert.equal(replayAfterRestart.acknowledgement.state,'duplicate');
  const otherTypeUnsigned={...base,recordId:'record:other-type',producer:{...base.producer,producerType:'prism'}};
  const otherType={...otherTypeUnsigned,recordDigest:producerRecordDigest(otherTypeUnsigned)};
  const otherTypeAdmission=await concurrentB.admit(canonicalJson(otherType));
  assert.equal(otherTypeAdmission.acknowledgement.state,'admitted','producer type must be part of the sequence-stream identity');
  const missingGap={schemaVersion:'producer-gap-report.v1' as const,producer:base.producer,pipelineRunId:'run:1',fromSequence:2,toSequence:2,state:'missing' as const,reportedAt:'2026-08-09T12:01:00Z',reasonCode:'delivery-gap'};
  await concurrentB.recordGap(missingGap);
  await assert.rejects(()=>concurrentB.recordGap({...missingGap,state:'restored',reportedAt:'2026-08-09T12:02:00Z'}),/OBSERVABILITY_GAP_RESTORATION_UNPROVED/,'a restored label cannot hide a missing durable record');
  await concurrentB.admit(canonicalJson(sequenceTwo));
  await concurrentB.recordGap({...missingGap,state:'restored',reportedAt:'2026-08-09T12:03:00Z'});
  assert.equal((await concurrentB.observabilityIssues('run:1')).missingRanges.length,0,'a gap clears only after its full durable sequence range arrives');
  console.log(JSON.stringify({ok:true,phase:'5.7-C',durableReplay:true,quarantine:true,bounded:true}));
}finally{fs.rmSync(root,{recursive:true,force:true});}
