import assert from 'node:assert/strict';
import fs from 'node:fs';
const inventory = JSON.parse(fs.readFileSync('docs/architecture/pipeline-test-gate-a11y-cutover-inventory.json', 'utf8'));
for (const file of inventory.legacyFilesToDelete) assert.equal(fs.existsSync(file), false, `legacy a11y file remains: ${file}`);
for (const file of inventory.replacementFilesRequired) assert.equal(fs.existsSync(file), true, `replacement missing: ${file}`);
assert.equal(fs.existsSync('contracts/pipeline-test-gate/v1/legacy-suite-bridge.json'), false);
assert.equal(fs.existsSync('skills/buster/plugins/buster-suite-runtime'), false);
const scaffold = fs.readFileSync('skills/nova/project_setup/tools/progress-scaffold-discovery.ts', 'utf8');
assert.match(scaffold, /uses: 'kubeclaw\.axe@1'/u); assert.match(scaffold, /LEGACY_A11Y_THRESHOLDS_RETIRED/u);
const realWorkspace = fs.readFileSync('tests/verification/e2e/real-run-workspace.mjs', 'utf8');
assert.match(realWorkspace, /axe: \{ uses: 'kubeclaw\.axe@1'/u);
assert.match(realWorkspace, /axe: \{ uses: 'kubeclaw\.axe@1'/u); assert.match(realWorkspace, /inputs: deploymentInput/u);
const entrypoint = fs.readFileSync('docker/buster-runtime-entrypoint.sh', 'utf8'); assert.match(entrypoint, /browser\.axe/u);
const role = JSON.parse(fs.readFileSync('packaging/runtime/roles/buster.json', 'utf8')); assert.equal(role.plugins.includes('kubeclaw.axe'), true);
const deploy = fs.readFileSync('scripts/deploy.sh', 'utf8');
assert.match(deploy, /cmd_nova_a11y_preflight/u); assert.match(deploy, /nova-a11y-preflight/u);
const preflight = fs.readFileSync('tests/verification/e2e/nova-a11y-production-preflight.mts', 'utf8');
assert.match(preflight, /createProductionNovaTestGate/u); assert.match(preflight, /'chromium', 'firefox', 'webkit'/u);
const status = JSON.parse(fs.readFileSync('docs/architecture/pipeline-test-gate-suite-migration-status.json', 'utf8'));
const suite = status.suites.find((item: any) => item.id === 'a11y'); assert.equal(suite.sourceCutover, 'complete'); assert.equal(suite.productionAcceptance, 'pending');
console.log(JSON.stringify({ ok: true, phase: 'a11y-cutover', authority: 'provider-plan-only' }));
