extends: default

rules:
  document-start: disable
  braces: disable
  colons: disable
  comments-indentation: disable
  line-length: disable
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
