import assert from 'node:assert/strict';
import { canonicalJson, sha256Text } from '@kubeclaw/plugin-sdk';
import {buildRequest,parseReport,validateBundle} from '../src/protocol.ts';
const execution={runId:'run:executor',stageId:'report',attemptId:'attempt:contract',attemptNumber:2};
const artifact={artifactId:'source',namespace:'kubeclaw.implementation-agent',mediaType:'application/json',digest:sha256Text('{}'),sizeBytes:2,producer:execution};
const source={runId:'run:fixture',journalHead:sha256Text('journal fixture'),snapshotDigest:sha256Text('snapshot fixture'),sourceStageId:'source',sourceRevision:'a'.repeat(40),artifacts:[artifact]};
const {artifacts,...target}=source;
const unsigned={schemaVersion:'report-source-bundle.v1',target,pipelineId:'fixture',evidence:[{evidenceId:sha256Text(canonicalJson(artifact)),artifact}],facts:[]};
const bundle={...unsigned,digest:sha256Text(canonicalJson(unsigned))};
const input={task:'Protocol contract test; no run authority asserted.',source};
assert.equal(buildRequest('agent',input,execution,bundle).protocol,'kubeclaw.pipeline-review.v4');
validateBundle(bundle,source);
assert.throws(()=>validateBundle({...bundle,pipelineId:'changed'},source));
const ids=bundle.evidence.map(item=>item.evidenceId);
const observations=['architecture','agents','prompts','tests','configuration'].map(dimension=>({dimension,finding:'Draft assessment.',priority:'low',evidenceIds:ids}));
const valid={status:'reviewed',summary:'Draft.',observations};
const parsed=parseReport(valid,input,execution,bundle);
assert.deepEqual(parsed.execution,execution); assert.deepEqual(parsed.sourceBundle,bundle);
assert.equal(parsed.narrativeStatus,'draft-not-entailment-verified');
for(const bad of [{...valid,identity:{runId:'foreign'}},{...valid,extra:true}]) assert.throws(()=>parseReport(bad,input,execution,bundle));
assert.throws(()=>parseReport({...valid,observations:observations.map(item=>({...item,evidenceIds:['foreign']}))},input,execution,bundle));
assert.throws(()=>parseReport({...valid,observations:observations.slice(1)},input,execution,bundle));
console.log(JSON.stringify({ok:true,plugin:'kubeclaw.pipeline-review',suite:'protocol'}));
