// Code generated from bundle JSON Schemas. DO NOT EDIT.
package telemetryv1

import "encoding/json"

var _ json.RawMessage

type RunManifestV1 struct {
	Extensions    json.RawMessage `json:"extensions,omitempty"`
	SchemaVersion string          `json:"schema_version"`
	Project       string          `json:"project"`
	RunId         string          `json:"run_id"`
	Fingerprint   string          `json:"fingerprint"`
	WorkItems     []struct {
		WorkType      string          `json:"work_type"`
		WorkId        string          `json:"work_id"`
		DependsOn     []string        `json:"depends_on"`
		Owner         string          `json:"owner"`
		Configuration json.RawMessage `json:"configuration"`
	} `json:"work_items"`
	ExecutionOrder  *[]string `json:"execution_order,omitempty"`
	DependencyEdges *[]struct {
		From string `json:"from"`
		To   string `json:"to"`
	} `json:"dependency_edges,omitempty"`
	RuntimePolicies json.RawMessage    `json:"runtime_policies,omitempty"`
	Models          *[]json.RawMessage `json:"models,omitempty"`
	Prompts         *[]json.RawMessage `json:"prompts,omitempty"`
	Tools           *[]json.RawMessage `json:"tools,omitempty"`
	Skills          *[]json.RawMessage `json:"skills,omitempty"`
	Plugins         *[]json.RawMessage `json:"plugins,omitempty"`
	Git             json.RawMessage    `json:"git,omitempty"`
	Deployment      json.RawMessage    `json:"deployment,omitempty"`
	Versions        json.RawMessage    `json:"versions,omitempty"`
	SchemaVersions  json.RawMessage    `json:"schema_versions"`
	CreatedAt       *string            `json:"created_at,omitempty"`
}

type RunArchiveManifestV1 struct {
	Extensions        json.RawMessage   `json:"extensions,omitempty"`
	SchemaVersion     string            `json:"schema_version"`
	RunId             string            `json:"run_id"`
	Project           string            `json:"project"`
	CreatedAt         *string           `json:"created_at,omitempty"`
	Lifecycle         json.RawMessage   `json:"lifecycle"`
	Sources           []json.RawMessage `json:"sources"`
	ManifestReference string            `json:"manifest_reference"`
	TerminalReference json.RawMessage   `json:"terminal_reference,omitempty"`
	Completeness      string            `json:"completeness"`
	RepairState       string            `json:"repair_state"`
	Sha256            string            `json:"sha256"`
}

type RunCatalogEntryV1 struct {
	Extensions       json.RawMessage `json:"extensions,omitempty"`
	SchemaVersion    string          `json:"schema_version"`
	RunId            string          `json:"run_id"`
	Project          string          `json:"project"`
	ArchiveReference string          `json:"archive_reference"`
	Sha256           string          `json:"sha256"`
	Completeness     string          `json:"completeness"`
	RepairState      string          `json:"repair_state"`
	RecordedAt       string          `json:"recorded_at"`
}

type ArtifactPublishedV1 struct {
	Extensions    json.RawMessage `json:"extensions,omitempty"`
	SchemaVersion string          `json:"schema_version"`
	ArtifactId    string          `json:"artifact_id"`
	LogicalId     string          `json:"logical_id"`
	Kind          string          `json:"kind"`
	MediaType     string          `json:"media_type"`
	ByteLength    json.Number     `json:"byte_length"`
	Sha256        string          `json:"sha256"`
	ContentClass  string          `json:"content_class"`
	Producer      string          `json:"producer"`
	Reference     string          `json:"reference"`
	Correlation   struct {
		AgentId         json.RawMessage `json:"agent_id,omitempty"`
		ModuleId        json.RawMessage `json:"module_id,omitempty"`
		GateType        json.RawMessage `json:"gate_type,omitempty"`
		ParentSessionId json.RawMessage `json:"parent_session_id,omitempty"`
		TraceId         json.RawMessage `json:"trace_id,omitempty"`
		SpanId          json.RawMessage `json:"span_id,omitempty"`
		ParentSpanId    json.RawMessage `json:"parent_span_id,omitempty"`
		Attempt         json.RawMessage `json:"attempt,omitempty"`
		DispatchId      json.RawMessage `json:"dispatch_id,omitempty"`
		GateId          json.RawMessage `json:"gate_id,omitempty"`
		ModelCallId     json.RawMessage `json:"model_call_id,omitempty"`
		Producer        string          `json:"producer"`
		Project         string          `json:"project"`
		RunId           string          `json:"run_id"`
		SessionId       json.RawMessage `json:"session_id,omitempty"`
		Source          string          `json:"source"`
		ToolCallId      json.RawMessage `json:"tool_call_id,omitempty"`
		WorkId          json.RawMessage `json:"work_id,omitempty"`
		WorkType        json.RawMessage `json:"work_type,omitempty"`
	} `json:"correlation"`
	Completeness       string          `json:"completeness"`
	OriginalByteLength *json.Number    `json:"original_byte_length"`
	OriginalSha256     *string         `json:"original_sha256"`
	Transformation     json.RawMessage `json:"transformation,omitempty"`
	PublishedAt        string          `json:"published_at"`
}

type ProducerHealthSnapshotV1 struct {
	Extensions    json.RawMessage `json:"extensions,omitempty"`
	SchemaVersion string          `json:"schema_version"`
	RunId         string          `json:"run_id"`
	GeneratedAt   string          `json:"generated_at"`
	Producers     []struct {
		ProducerId             string          `json:"producer_id"`
		Status                 string          `json:"status"`
		LastSuccessfulEmission *string         `json:"last_successful_emission"`
		Lag                    *json.Number    `json:"lag"`
		Checkpoint             *string         `json:"checkpoint"`
		InvalidCount           json.Number     `json:"invalid_count"`
		QuarantinedCount       json.Number     `json:"quarantined_count"`
		DeadLetterCount        json.Number     `json:"dead_letter_count"`
		MissingPayloadCount    json.Number     `json:"missing_payload_count"`
		RestartCount           json.Number     `json:"restart_count"`
		Reconciliation         json.RawMessage `json:"reconciliation"`
		DegradationIntervals   *[]struct {
			StartedAt  string          `json:"started_at"`
			EndedAt    json.RawMessage `json:"ended_at,omitempty"`
			ReasonCode string          `json:"reason_code"`
		} `json:"degradation_intervals,omitempty"`
		Capabilities []struct {
			Capability string          `json:"capability"`
			Status     string          `json:"status"`
			ReasonCode *string         `json:"reason_code"`
			Details    json.RawMessage `json:"details,omitempty"`
		} `json:"capabilities"`
	} `json:"producers"`
	Completeness string `json:"completeness"`
}

type TerminalClosureV1 struct {
	Extensions               json.RawMessage `json:"extensions,omitempty"`
	SchemaVersion            string          `json:"schema_version"`
	RunId                    string          `json:"run_id"`
	Project                  string          `json:"project"`
	ClosedAt                 string          `json:"closed_at"`
	Outcome                  string          `json:"outcome"`
	ReasonCode               string          `json:"reason_code"`
	DurationMs               json.RawMessage `json:"duration_ms,omitempty"`
	Counts                   json.RawMessage `json:"counts,omitempty"`
	Cost                     json.RawMessage `json:"cost,omitempty"`
	LastWorkId               json.RawMessage `json:"last_work_id,omitempty"`
	ManifestFingerprint      string          `json:"manifest_fingerprint"`
	Observability            string          `json:"observability"`
	SummaryReference         json.RawMessage `json:"summary_reference,omitempty"`
	ArtifactCatalogReference string          `json:"artifact_catalog_reference"`
}

type PipelineLifecycleEventV1 struct {
	Extensions       json.RawMessage `json:"extensions,omitempty"`
	SchemaVersion    string          `json:"schema_version"`
	EventId          string          `json:"event_id"`
	SourceEventId    string          `json:"source_event_id"`
	RunId            string          `json:"run_id"`
	Project          string          `json:"project"`
	WorkId           json.RawMessage `json:"work_id,omitempty"`
	WorkType         json.RawMessage `json:"work_type,omitempty"`
	ModuleId         json.RawMessage `json:"module_id,omitempty"`
	GateId           json.RawMessage `json:"gate_id,omitempty"`
	Attempt          json.RawMessage `json:"attempt,omitempty"`
	LifecycleVersion string          `json:"lifecycle_version"`
	EffectiveAt      string          `json:"effective_at"`
	Authority        string          `json:"authority"`
	PreviousState    *string         `json:"previous_state"`
	NewState         string          `json:"new_state"`
	ReasonCode       string          `json:"reason_code"`
	Data             json.RawMessage `json:"data,omitempty"`
}

type PipelineLifecycleReadModelsV1 struct {
	Extensions    json.RawMessage `json:"extensions,omitempty"`
	SchemaVersion string          `json:"schema_version"`
	RunId         string          `json:"run_id"`
	Pipeline      *struct {
		Status            string             `json:"status"`
		RunId             json.RawMessage    `json:"run_id,omitempty"`
		RunRef            json.RawMessage    `json:"run_ref,omitempty"`
		WorkId            json.RawMessage    `json:"work_id,omitempty"`
		ModuleId          json.RawMessage    `json:"module_id,omitempty"`
		GateId            json.RawMessage    `json:"gate_id,omitempty"`
		GateType          json.RawMessage    `json:"gate_type,omitempty"`
		Title             json.RawMessage    `json:"title,omitempty"`
		ModuleDir         json.RawMessage    `json:"module_dir,omitempty"`
		Attempt           json.RawMessage    `json:"attempt,omitempty"`
		CurrentAttempt    json.RawMessage    `json:"current_attempt,omitempty"`
		PreviousState     json.RawMessage    `json:"previous_state,omitempty"`
		ReasonCode        json.RawMessage    `json:"reason_code,omitempty"`
		HaltReason        json.RawMessage    `json:"halt_reason,omitempty"`
		TerminalStatus    json.RawMessage    `json:"terminal_status,omitempty"`
		TerminalDecision  json.RawMessage    `json:"terminal_decision,omitempty"`
		RunMode           json.RawMessage    `json:"run_mode,omitempty"`
		Resume            json.RawMessage    `json:"resume,omitempty"`
		RequestedModuleId json.RawMessage    `json:"requested_module_id,omitempty"`
		Entrypoint        json.RawMessage    `json:"entrypoint,omitempty"`
		CurrentPhase      json.RawMessage    `json:"current_phase,omitempty"`
		StartedAt         json.RawMessage    `json:"started_at,omitempty"`
		AttemptStartedAt  json.RawMessage    `json:"attempt_started_at,omitempty"`
		PhaseStartedAt    json.RawMessage    `json:"phase_started_at,omitempty"`
		CompletedAt       json.RawMessage    `json:"completed_at,omitempty"`
		CompletionSummary json.RawMessage    `json:"completion_summary,omitempty"`
		FailCount         json.RawMessage    `json:"fail_count,omitempty"`
		FailSummaries     *[]json.RawMessage `json:"fail_summaries,omitempty"`
		LastFailure       json.RawMessage    `json:"last_failure,omitempty"`
		BlockedAt         json.RawMessage    `json:"blocked_at,omitempty"`
		BlockedReason     json.RawMessage    `json:"blocked_reason,omitempty"`
		BlockedPhase      json.RawMessage    `json:"blocked_phase,omitempty"`
		BlockedFailCount  json.RawMessage    `json:"blocked_fail_count,omitempty"`
		DispatchId        json.RawMessage    `json:"dispatch_id,omitempty"`
		GatewayLabel      json.RawMessage    `json:"gateway_label,omitempty"`
		SessionId         json.RawMessage    `json:"session_id,omitempty"`
		SessionKey        json.RawMessage    `json:"session_key,omitempty"`
		Model             json.RawMessage    `json:"model,omitempty"`
		CommitHash        json.RawMessage    `json:"commit_hash,omitempty"`
		History           *[]struct {
			Timestamp *string         `json:"timestamp,omitempty"`
			From      json.RawMessage `json:"from,omitempty"`
			To        json.RawMessage `json:"to,omitempty"`
			Agent     json.RawMessage `json:"agent,omitempty"`
			Note      json.RawMessage `json:"note,omitempty"`
		} `json:"history,omitempty"`
		Validation       json.RawMessage `json:"validation,omitempty"`
		ProjectionSource json.RawMessage `json:"projection_source,omitempty"`
		LatestEventType  json.RawMessage `json:"latest_event_type,omitempty"`
		LatestEventAt    json.RawMessage `json:"latest_event_at,omitempty"`
		LastEventId      json.RawMessage `json:"last_event_id,omitempty"`
		LastEffectiveAt  json.RawMessage `json:"last_effective_at,omitempty"`
		LifecycleVersion json.RawMessage `json:"lifecycle_version,omitempty"`
	} `json:"pipeline"`
	Modules map[string]struct {
		Status            string             `json:"status"`
		RunId             json.RawMessage    `json:"run_id,omitempty"`
		RunRef            json.RawMessage    `json:"run_ref,omitempty"`
		WorkId            json.RawMessage    `json:"work_id,omitempty"`
		ModuleId          json.RawMessage    `json:"module_id,omitempty"`
		GateId            json.RawMessage    `json:"gate_id,omitempty"`
		GateType          json.RawMessage    `json:"gate_type,omitempty"`
		Title             json.RawMessage    `json:"title,omitempty"`
		ModuleDir         json.RawMessage    `json:"module_dir,omitempty"`
		Attempt           json.RawMessage    `json:"attempt,omitempty"`
		CurrentAttempt    json.RawMessage    `json:"current_attempt,omitempty"`
		PreviousState     json.RawMessage    `json:"previous_state,omitempty"`
		ReasonCode        json.RawMessage    `json:"reason_code,omitempty"`
		HaltReason        json.RawMessage    `json:"halt_reason,omitempty"`
		TerminalStatus    json.RawMessage    `json:"terminal_status,omitempty"`
		TerminalDecision  json.RawMessage    `json:"terminal_decision,omitempty"`
		RunMode           json.RawMessage    `json:"run_mode,omitempty"`
		Resume            json.RawMessage    `json:"resume,omitempty"`
		RequestedModuleId json.RawMessage    `json:"requested_module_id,omitempty"`
		Entrypoint        json.RawMessage    `json:"entrypoint,omitempty"`
		CurrentPhase      json.RawMessage    `json:"current_phase,omitempty"`
		StartedAt         json.RawMessage    `json:"started_at,omitempty"`
		AttemptStartedAt  json.RawMessage    `json:"attempt_started_at,omitempty"`
		PhaseStartedAt    json.RawMessage    `json:"phase_started_at,omitempty"`
		CompletedAt       json.RawMessage    `json:"completed_at,omitempty"`
		CompletionSummary json.RawMessage    `json:"completion_summary,omitempty"`
		FailCount         json.RawMessage    `json:"fail_count,omitempty"`
		FailSummaries     *[]json.RawMessage `json:"fail_summaries,omitempty"`
		LastFailure       json.RawMessage    `json:"last_failure,omitempty"`
		BlockedAt         json.RawMessage    `json:"blocked_at,omitempty"`
		BlockedReason     json.RawMessage    `json:"blocked_reason,omitempty"`
		BlockedPhase      json.RawMessage    `json:"blocked_phase,omitempty"`
		BlockedFailCount  json.RawMessage    `json:"blocked_fail_count,omitempty"`
		DispatchId        json.RawMessage    `json:"dispatch_id,omitempty"`
		GatewayLabel      json.RawMessage    `json:"gateway_label,omitempty"`
		SessionId         json.RawMessage    `json:"session_id,omitempty"`
		SessionKey        json.RawMessage    `json:"session_key,omitempty"`
		Model             json.RawMessage    `json:"model,omitempty"`
		CommitHash        json.RawMessage    `json:"commit_hash,omitempty"`
		History           *[]struct {
			Timestamp *string         `json:"timestamp,omitempty"`
			From      json.RawMessage `json:"from,omitempty"`
			To        json.RawMessage `json:"to,omitempty"`
			Agent     json.RawMessage `json:"agent,omitempty"`
			Note      json.RawMessage `json:"note,omitempty"`
		} `json:"history,omitempty"`
		Validation       json.RawMessage `json:"validation,omitempty"`
		ProjectionSource json.RawMessage `json:"projection_source,omitempty"`
		LatestEventType  json.RawMessage `json:"latest_event_type,omitempty"`
		LatestEventAt    json.RawMessage `json:"latest_event_at,omitempty"`
		LastEventId      json.RawMessage `json:"last_event_id,omitempty"`
		LastEffectiveAt  json.RawMessage `json:"last_effective_at,omitempty"`
		LifecycleVersion json.RawMessage `json:"lifecycle_version,omitempty"`
	} `json:"modules"`
	Gates map[string]struct {
		Status            string             `json:"status"`
		RunId             json.RawMessage    `json:"run_id,omitempty"`
		RunRef            json.RawMessage    `json:"run_ref,omitempty"`
		WorkId            json.RawMessage    `json:"work_id,omitempty"`
		ModuleId          json.RawMessage    `json:"module_id,omitempty"`
		GateId            json.RawMessage    `json:"gate_id,omitempty"`
		GateType          json.RawMessage    `json:"gate_type,omitempty"`
		Title             json.RawMessage    `json:"title,omitempty"`
		ModuleDir         json.RawMessage    `json:"module_dir,omitempty"`
		Attempt           json.RawMessage    `json:"attempt,omitempty"`
		CurrentAttempt    json.RawMessage    `json:"current_attempt,omitempty"`
		PreviousState     json.RawMessage    `json:"previous_state,omitempty"`
		ReasonCode        json.RawMessage    `json:"reason_code,omitempty"`
		HaltReason        json.RawMessage    `json:"halt_reason,omitempty"`
		TerminalStatus    json.RawMessage    `json:"terminal_status,omitempty"`
		TerminalDecision  json.RawMessage    `json:"terminal_decision,omitempty"`
		RunMode           json.RawMessage    `json:"run_mode,omitempty"`
		Resume            json.RawMessage    `json:"resume,omitempty"`
		RequestedModuleId json.RawMessage    `json:"requested_module_id,omitempty"`
		Entrypoint        json.RawMessage    `json:"entrypoint,omitempty"`
		CurrentPhase      json.RawMessage    `json:"current_phase,omitempty"`
		StartedAt         json.RawMessage    `json:"started_at,omitempty"`
		AttemptStartedAt  json.RawMessage    `json:"attempt_started_at,omitempty"`
		PhaseStartedAt    json.RawMessage    `json:"phase_started_at,omitempty"`
		CompletedAt       json.RawMessage    `json:"completed_at,omitempty"`
		CompletionSummary json.RawMessage    `json:"completion_summary,omitempty"`
		FailCount         json.RawMessage    `json:"fail_count,omitempty"`
		FailSummaries     *[]json.RawMessage `json:"fail_summaries,omitempty"`
		LastFailure       json.RawMessage    `json:"last_failure,omitempty"`
		BlockedAt         json.RawMessage    `json:"blocked_at,omitempty"`
		BlockedReason     json.RawMessage    `json:"blocked_reason,omitempty"`
		BlockedPhase      json.RawMessage    `json:"blocked_phase,omitempty"`
		BlockedFailCount  json.RawMessage    `json:"blocked_fail_count,omitempty"`
		DispatchId        json.RawMessage    `json:"dispatch_id,omitempty"`
		GatewayLabel      json.RawMessage    `json:"gateway_label,omitempty"`
		SessionId         json.RawMessage    `json:"session_id,omitempty"`
		SessionKey        json.RawMessage    `json:"session_key,omitempty"`
		Model             json.RawMessage    `json:"model,omitempty"`
		CommitHash        json.RawMessage    `json:"commit_hash,omitempty"`
		History           *[]struct {
			Timestamp *string         `json:"timestamp,omitempty"`
			From      json.RawMessage `json:"from,omitempty"`
			To        json.RawMessage `json:"to,omitempty"`
			Agent     json.RawMessage `json:"agent,omitempty"`
			Note      json.RawMessage `json:"note,omitempty"`
		} `json:"history,omitempty"`
		Validation       json.RawMessage `json:"validation,omitempty"`
		ProjectionSource json.RawMessage `json:"projection_source,omitempty"`
		LatestEventType  json.RawMessage `json:"latest_event_type,omitempty"`
		LatestEventAt    json.RawMessage `json:"latest_event_at,omitempty"`
		LastEventId      json.RawMessage `json:"last_event_id,omitempty"`
		LastEffectiveAt  json.RawMessage `json:"last_effective_at,omitempty"`
		LifecycleVersion json.RawMessage `json:"lifecycle_version,omitempty"`
	} `json:"gates"`
	Generators *map[string]struct {
		Status            string             `json:"status"`
		RunId             json.RawMessage    `json:"run_id,omitempty"`
		RunRef            json.RawMessage    `json:"run_ref,omitempty"`
		WorkId            json.RawMessage    `json:"work_id,omitempty"`
		ModuleId          json.RawMessage    `json:"module_id,omitempty"`
		GateId            json.RawMessage    `json:"gate_id,omitempty"`
		GateType          json.RawMessage    `json:"gate_type,omitempty"`
		Title             json.RawMessage    `json:"title,omitempty"`
		ModuleDir         json.RawMessage    `json:"module_dir,omitempty"`
		Attempt           json.RawMessage    `json:"attempt,omitempty"`
		CurrentAttempt    json.RawMessage    `json:"current_attempt,omitempty"`
		PreviousState     json.RawMessage    `json:"previous_state,omitempty"`
		ReasonCode        json.RawMessage    `json:"reason_code,omitempty"`
		HaltReason        json.RawMessage    `json:"halt_reason,omitempty"`
		TerminalStatus    json.RawMessage    `json:"terminal_status,omitempty"`
		TerminalDecision  json.RawMessage    `json:"terminal_decision,omitempty"`
		RunMode           json.RawMessage    `json:"run_mode,omitempty"`
		Resume            json.RawMessage    `json:"resume,omitempty"`
		RequestedModuleId json.RawMessage    `json:"requested_module_id,omitempty"`
		Entrypoint        json.RawMessage    `json:"entrypoint,omitempty"`
		CurrentPhase      json.RawMessage    `json:"current_phase,omitempty"`
		StartedAt         json.RawMessage    `json:"started_at,omitempty"`
		AttemptStartedAt  json.RawMessage    `json:"attempt_started_at,omitempty"`
		PhaseStartedAt    json.RawMessage    `json:"phase_started_at,omitempty"`
		CompletedAt       json.RawMessage    `json:"completed_at,omitempty"`
		CompletionSummary json.RawMessage    `json:"completion_summary,omitempty"`
		FailCount         json.RawMessage    `json:"fail_count,omitempty"`
		FailSummaries     *[]json.RawMessage `json:"fail_summaries,omitempty"`
		LastFailure       json.RawMessage    `json:"last_failure,omitempty"`
		BlockedAt         json.RawMessage    `json:"blocked_at,omitempty"`
		BlockedReason     json.RawMessage    `json:"blocked_reason,omitempty"`
		BlockedPhase      json.RawMessage    `json:"blocked_phase,omitempty"`
		BlockedFailCount  json.RawMessage    `json:"blocked_fail_count,omitempty"`
		DispatchId        json.RawMessage    `json:"dispatch_id,omitempty"`
		GatewayLabel      json.RawMessage    `json:"gateway_label,omitempty"`
		SessionId         json.RawMessage    `json:"session_id,omitempty"`
		SessionKey        json.RawMessage    `json:"session_key,omitempty"`
		Model             json.RawMessage    `json:"model,omitempty"`
		CommitHash        json.RawMessage    `json:"commit_hash,omitempty"`
		History           *[]struct {
			Timestamp *string         `json:"timestamp,omitempty"`
			From      json.RawMessage `json:"from,omitempty"`
			To        json.RawMessage `json:"to,omitempty"`
			Agent     json.RawMessage `json:"agent,omitempty"`
			Note      json.RawMessage `json:"note,omitempty"`
		} `json:"history,omitempty"`
		Validation       json.RawMessage `json:"validation,omitempty"`
		ProjectionSource json.RawMessage `json:"projection_source,omitempty"`
		LatestEventType  json.RawMessage `json:"latest_event_type,omitempty"`
		LatestEventAt    json.RawMessage `json:"latest_event_at,omitempty"`
		LastEventId      json.RawMessage `json:"last_event_id,omitempty"`
		LastEffectiveAt  json.RawMessage `json:"last_effective_at,omitempty"`
		LifecycleVersion json.RawMessage `json:"lifecycle_version,omitempty"`
	} `json:"generators,omitempty"`
	Validators *map[string]struct {
		Status            string             `json:"status"`
		RunId             json.RawMessage    `json:"run_id,omitempty"`
		RunRef            json.RawMessage    `json:"run_ref,omitempty"`
		WorkId            json.RawMessage    `json:"work_id,omitempty"`
		ModuleId          json.RawMessage    `json:"module_id,omitempty"`
		GateId            json.RawMessage    `json:"gate_id,omitempty"`
		GateType          json.RawMessage    `json:"gate_type,omitempty"`
		Title             json.RawMessage    `json:"title,omitempty"`
		ModuleDir         json.RawMessage    `json:"module_dir,omitempty"`
		Attempt           json.RawMessage    `json:"attempt,omitempty"`
		CurrentAttempt    json.RawMessage    `json:"current_attempt,omitempty"`
		PreviousState     json.RawMessage    `json:"previous_state,omitempty"`
		ReasonCode        json.RawMessage    `json:"reason_code,omitempty"`
		HaltReason        json.RawMessage    `json:"halt_reason,omitempty"`
		TerminalStatus    json.RawMessage    `json:"terminal_status,omitempty"`
		TerminalDecision  json.RawMessage    `json:"terminal_decision,omitempty"`
		RunMode           json.RawMessage    `json:"run_mode,omitempty"`
		Resume            json.RawMessage    `json:"resume,omitempty"`
		RequestedModuleId json.RawMessage    `json:"requested_module_id,omitempty"`
		Entrypoint        json.RawMessage    `json:"entrypoint,omitempty"`
		CurrentPhase      json.RawMessage    `json:"current_phase,omitempty"`
		StartedAt         json.RawMessage    `json:"started_at,omitempty"`
		AttemptStartedAt  json.RawMessage    `json:"attempt_started_at,omitempty"`
		PhaseStartedAt    json.RawMessage    `json:"phase_started_at,omitempty"`
		CompletedAt       json.RawMessage    `json:"completed_at,omitempty"`
		CompletionSummary json.RawMessage    `json:"completion_summary,omitempty"`
		FailCount         json.RawMessage    `json:"fail_count,omitempty"`
		FailSummaries     *[]json.RawMessage `json:"fail_summaries,omitempty"`
		LastFailure       json.RawMessage    `json:"last_failure,omitempty"`
		BlockedAt         json.RawMessage    `json:"blocked_at,omitempty"`
		BlockedReason     json.RawMessage    `json:"blocked_reason,omitempty"`
		BlockedPhase      json.RawMessage    `json:"blocked_phase,omitempty"`
		BlockedFailCount  json.RawMessage    `json:"blocked_fail_count,omitempty"`
		DispatchId        json.RawMessage    `json:"dispatch_id,omitempty"`
		GatewayLabel      json.RawMessage    `json:"gateway_label,omitempty"`
		SessionId         json.RawMessage    `json:"session_id,omitempty"`
		SessionKey        json.RawMessage    `json:"session_key,omitempty"`
		Model             json.RawMessage    `json:"model,omitempty"`
		CommitHash        json.RawMessage    `json:"commit_hash,omitempty"`
		History           *[]struct {
			Timestamp *string         `json:"timestamp,omitempty"`
			From      json.RawMessage `json:"from,omitempty"`
			To        json.RawMessage `json:"to,omitempty"`
			Agent     json.RawMessage `json:"agent,omitempty"`
			Note      json.RawMessage `json:"note,omitempty"`
		} `json:"history,omitempty"`
		Validation       json.RawMessage `json:"validation,omitempty"`
		ProjectionSource json.RawMessage `json:"projection_source,omitempty"`
		LatestEventType  json.RawMessage `json:"latest_event_type,omitempty"`
		LatestEventAt    json.RawMessage `json:"latest_event_at,omitempty"`
		LastEventId      json.RawMessage `json:"last_event_id,omitempty"`
		LastEffectiveAt  json.RawMessage `json:"last_effective_at,omitempty"`
		LifecycleVersion json.RawMessage `json:"lifecycle_version,omitempty"`
	} `json:"validators,omitempty"`
	PipelineSteps *map[string]struct {
		Status            string             `json:"status"`
		RunId             json.RawMessage    `json:"run_id,omitempty"`
		RunRef            json.RawMessage    `json:"run_ref,omitempty"`
		WorkId            json.RawMessage    `json:"work_id,omitempty"`
		ModuleId          json.RawMessage    `json:"module_id,omitempty"`
		GateId            json.RawMessage    `json:"gate_id,omitempty"`
		GateType          json.RawMessage    `json:"gate_type,omitempty"`
		Title             json.RawMessage    `json:"title,omitempty"`
		ModuleDir         json.RawMessage    `json:"module_dir,omitempty"`
		Attempt           json.RawMessage    `json:"attempt,omitempty"`
		CurrentAttempt    json.RawMessage    `json:"current_attempt,omitempty"`
		PreviousState     json.RawMessage    `json:"previous_state,omitempty"`
		ReasonCode        json.RawMessage    `json:"reason_code,omitempty"`
		HaltReason        json.RawMessage    `json:"halt_reason,omitempty"`
		TerminalStatus    json.RawMessage    `json:"terminal_status,omitempty"`
		TerminalDecision  json.RawMessage    `json:"terminal_decision,omitempty"`
		RunMode           json.RawMessage    `json:"run_mode,omitempty"`
		Resume            json.RawMessage    `json:"resume,omitempty"`
		RequestedModuleId json.RawMessage    `json:"requested_module_id,omitempty"`
		Entrypoint        json.RawMessage    `json:"entrypoint,omitempty"`
		CurrentPhase      json.RawMessage    `json:"current_phase,omitempty"`
		StartedAt         json.RawMessage    `json:"started_at,omitempty"`
		AttemptStartedAt  json.RawMessage    `json:"attempt_started_at,omitempty"`
		PhaseStartedAt    json.RawMessage    `json:"phase_started_at,omitempty"`
		CompletedAt       json.RawMessage    `json:"completed_at,omitempty"`
		CompletionSummary json.RawMessage    `json:"completion_summary,omitempty"`
		FailCount         json.RawMessage    `json:"fail_count,omitempty"`
		FailSummaries     *[]json.RawMessage `json:"fail_summaries,omitempty"`
		LastFailure       json.RawMessage    `json:"last_failure,omitempty"`
		BlockedAt         json.RawMessage    `json:"blocked_at,omitempty"`
		BlockedReason     json.RawMessage    `json:"blocked_reason,omitempty"`
		BlockedPhase      json.RawMessage    `json:"blocked_phase,omitempty"`
		BlockedFailCount  json.RawMessage    `json:"blocked_fail_count,omitempty"`
		DispatchId        json.RawMessage    `json:"dispatch_id,omitempty"`
		GatewayLabel      json.RawMessage    `json:"gateway_label,omitempty"`
		SessionId         json.RawMessage    `json:"session_id,omitempty"`
		SessionKey        json.RawMessage    `json:"session_key,omitempty"`
		Model             json.RawMessage    `json:"model,omitempty"`
		CommitHash        json.RawMessage    `json:"commit_hash,omitempty"`
		History           *[]struct {
			Timestamp *string         `json:"timestamp,omitempty"`
			From      json.RawMessage `json:"from,omitempty"`
			To        json.RawMessage `json:"to,omitempty"`
			Agent     json.RawMessage `json:"agent,omitempty"`
			Note      json.RawMessage `json:"note,omitempty"`
		} `json:"history,omitempty"`
		Validation       json.RawMessage `json:"validation,omitempty"`
		ProjectionSource json.RawMessage `json:"projection_source,omitempty"`
		LatestEventType  json.RawMessage `json:"latest_event_type,omitempty"`
		LatestEventAt    json.RawMessage `json:"latest_event_at,omitempty"`
		LastEventId      json.RawMessage `json:"last_event_id,omitempty"`
		LastEffectiveAt  json.RawMessage `json:"last_effective_at,omitempty"`
		LifecycleVersion json.RawMessage `json:"lifecycle_version,omitempty"`
	} `json:"pipeline_steps,omitempty"`
	Attempts map[string]struct {
		AttemptId       string          `json:"attempt_id"`
		WorkId          string          `json:"work_id"`
		WorkType        string          `json:"work_type"`
		Attempt         json.Number     `json:"attempt"`
		Status          string          `json:"status"`
		ReasonCode      json.RawMessage `json:"reason_code,omitempty"`
		DispatchId      json.RawMessage `json:"dispatch_id,omitempty"`
		SessionId       json.RawMessage `json:"session_id,omitempty"`
		LastEventId     string          `json:"last_event_id"`
		LastEffectiveAt string          `json:"last_effective_at"`
	} `json:"attempts"`
	Progression *struct {
		ModulesTotal   json.Number `json:"modules_total"`
		ModulesPassed  json.Number `json:"modules_passed"`
		ModulesFailed  json.Number `json:"modules_failed"`
		ModulesBlocked json.Number `json:"modules_blocked"`
		ModulesActive  json.Number `json:"modules_active"`
	} `json:"progression,omitempty"`
	Waits            *map[string]json.RawMessage `json:"waits,omitempty"`
	Signals          *map[string]json.RawMessage `json:"signals,omitempty"`
	ActiveSessions   *map[string]json.RawMessage `json:"active_sessions,omitempty"`
	Cooldowns        *map[string]json.RawMessage `json:"cooldowns,omitempty"`
	GeneratedAt      *string                     `json:"generated_at,omitempty"`
	LastEventId      json.RawMessage             `json:"last_event_id,omitempty"`
	LastEventType    json.RawMessage             `json:"last_event_type,omitempty"`
	EventCount       *json.Number                `json:"event_count,omitempty"`
	LifecycleVersion *string                     `json:"lifecycle_version,omitempty"`
	LastCursor       json.RawMessage             `json:"last_cursor,omitempty"`
}

type EvaluationFactV1 struct {
	Extensions    json.RawMessage `json:"extensions,omitempty"`
	SchemaVersion string          `json:"schema_version"`
	RecordedAt    string          `json:"recorded_at"`
	RunId         string          `json:"run_id"`
	Project       *string         `json:"project,omitempty"`
	WorkId        json.RawMessage `json:"work_id,omitempty"`
	Attempt       json.RawMessage `json:"attempt,omitempty"`
	Dimension     string          `json:"dimension"`
	Value         json.RawMessage `json:"value"`
	Fingerprint   json.RawMessage `json:"fingerprint,omitempty"`
}

type PipelineCommandEvidenceV1 struct {
	Extensions               json.RawMessage `json:"extensions,omitempty"`
	SchemaVersion            string          `json:"schema_version"`
	State                    string          `json:"state"`
	RecordedAt               string          `json:"recorded_at"`
	CommandId                string          `json:"command_id"`
	CommandType              string          `json:"command_type"`
	Actor                    string          `json:"actor"`
	Capability               *string         `json:"capability,omitempty"`
	Target                   json.RawMessage `json:"target,omitempty"`
	ExpectedLifecycleVersion *json.Number    `json:"expected_lifecycle_version,omitempty"`
	Reason                   string          `json:"reason"`
	ReasonCode               json.RawMessage `json:"reason_code,omitempty"`
	Result                   json.RawMessage `json:"result,omitempty"`
	CommandHash              string          `json:"command_hash"`
}

type RuntimeLogV1 struct {
	Extensions    json.RawMessage `json:"extensions,omitempty"`
	SchemaVersion string          `json:"schema_version"`
	Timestamp     string          `json:"timestamp"`
	Level         string          `json:"level"`
	Component     string          `json:"component"`
	Message       string          `json:"message"`
	Project       json.RawMessage `json:"project,omitempty"`
	RunId         json.RawMessage `json:"run_id,omitempty"`
	WorkId        json.RawMessage `json:"work_id,omitempty"`
	ErrorClass    json.RawMessage `json:"error_class,omitempty"`
	ReasonCode    json.RawMessage `json:"reason_code,omitempty"`
}

type QuarantinedPayloadV1 struct {
	Extensions         json.RawMessage `json:"extensions,omitempty"`
	SchemaVersion      string          `json:"schema_version"`
	QuarantineId       string          `json:"quarantine_id"`
	QuarantinedAt      string          `json:"quarantined_at"`
	ReasonCode         string          `json:"reason_code"`
	Producer           string          `json:"producer"`
	Identity           json.RawMessage `json:"identity,omitempty"`
	OriginalByteLength json.RawMessage `json:"original_byte_length,omitempty"`
	OriginalSha256     json.RawMessage `json:"original_sha256,omitempty"`
	IntendedType       json.RawMessage `json:"intended_type,omitempty"`
}

type PipelineEvidenceExportV1 struct {
	Extensions                   json.RawMessage `json:"extensions,omitempty"`
	SchemaVersion                string          `json:"schema_version"`
	ExportedAt                   string          `json:"exported_at"`
	SourceRunId                  string          `json:"source_run_id"`
	Verification                 json.RawMessage `json:"verification"`
	ContractsReference           string          `json:"contracts_reference"`
	ContractManifestReference    string          `json:"contract_manifest_reference"`
	ExpectedSourceFactsReference *string         `json:"expected_source_facts_reference,omitempty"`
	SourceGitCommit              string          `json:"source_git_commit"`
	SourceGitClean               bool            `json:"source_git_clean"`
	BundleSha256                 string          `json:"bundle_sha256"`
	HashAlgorithm                string          `json:"hash_algorithm"`
}

type ExpectedSourceFactsV1 struct {
	Extensions          json.RawMessage `json:"extensions,omitempty"`
	SchemaVersion       string          `json:"schema_version"`
	RunId               string          `json:"run_id"`
	Project             string          `json:"project"`
	EventTypes          []string        `json:"event_types"`
	ReadinessEventTypes []string        `json:"readiness_event_types"`
	ArtifactKinds       []string        `json:"artifact_kinds"`
	LifecycleProjection struct {
		SchemaVersion    string          `json:"schema_version"`
		RunId            string          `json:"run_id"`
		LifecycleVersion *string         `json:"lifecycle_version,omitempty"`
		LastCursor       json.RawMessage `json:"last_cursor,omitempty"`
		Pipeline         *struct {
			Status            string             `json:"status"`
			RunId             json.RawMessage    `json:"run_id,omitempty"`
			RunRef            json.RawMessage    `json:"run_ref,omitempty"`
			WorkId            json.RawMessage    `json:"work_id,omitempty"`
			ModuleId          json.RawMessage    `json:"module_id,omitempty"`
			GateId            json.RawMessage    `json:"gate_id,omitempty"`
			GateType          json.RawMessage    `json:"gate_type,omitempty"`
			Title             json.RawMessage    `json:"title,omitempty"`
			ModuleDir         json.RawMessage    `json:"module_dir,omitempty"`
			Attempt           json.RawMessage    `json:"attempt,omitempty"`
			CurrentAttempt    json.RawMessage    `json:"current_attempt,omitempty"`
			PreviousState     json.RawMessage    `json:"previous_state,omitempty"`
			ReasonCode        json.RawMessage    `json:"reason_code,omitempty"`
			HaltReason        json.RawMessage    `json:"halt_reason,omitempty"`
			TerminalStatus    json.RawMessage    `json:"terminal_status,omitempty"`
			TerminalDecision  json.RawMessage    `json:"terminal_decision,omitempty"`
			RunMode           json.RawMessage    `json:"run_mode,omitempty"`
			Resume            json.RawMessage    `json:"resume,omitempty"`
			RequestedModuleId json.RawMessage    `json:"requested_module_id,omitempty"`
			Entrypoint        json.RawMessage    `json:"entrypoint,omitempty"`
			CurrentPhase      json.RawMessage    `json:"current_phase,omitempty"`
			StartedAt         json.RawMessage    `json:"started_at,omitempty"`
			AttemptStartedAt  json.RawMessage    `json:"attempt_started_at,omitempty"`
			PhaseStartedAt    json.RawMessage    `json:"phase_started_at,omitempty"`
			CompletedAt       json.RawMessage    `json:"completed_at,omitempty"`
			CompletionSummary json.RawMessage    `json:"completion_summary,omitempty"`
			FailCount         json.RawMessage    `json:"fail_count,omitempty"`
			FailSummaries     *[]json.RawMessage `json:"fail_summaries,omitempty"`
			LastFailure       json.RawMessage    `json:"last_failure,omitempty"`
			BlockedAt         json.RawMessage    `json:"blocked_at,omitempty"`
			BlockedReason     json.RawMessage    `json:"blocked_reason,omitempty"`
			BlockedPhase      json.RawMessage    `json:"blocked_phase,omitempty"`
			BlockedFailCount  json.RawMessage    `json:"blocked_fail_count,omitempty"`
			DispatchId        json.RawMessage    `json:"dispatch_id,omitempty"`
			GatewayLabel      json.RawMessage    `json:"gateway_label,omitempty"`
			SessionId         json.RawMessage    `json:"session_id,omitempty"`
			SessionKey        json.RawMessage    `json:"session_key,omitempty"`
			Model             json.RawMessage    `json:"model,omitempty"`
			CommitHash        json.RawMessage    `json:"commit_hash,omitempty"`
			History           *[]struct {
				Timestamp *string         `json:"timestamp,omitempty"`
				From      json.RawMessage `json:"from,omitempty"`
				To        json.RawMessage `json:"to,omitempty"`
				Agent     json.RawMessage `json:"agent,omitempty"`
				Note      json.RawMessage `json:"note,omitempty"`
			} `json:"history,omitempty"`
			Validation       json.RawMessage `json:"validation,omitempty"`
			ProjectionSource json.RawMessage `json:"projection_source,omitempty"`
			LatestEventType  json.RawMessage `json:"latest_event_type,omitempty"`
			LatestEventAt    json.RawMessage `json:"latest_event_at,omitempty"`
			LastEventId      json.RawMessage `json:"last_event_id,omitempty"`
			LastEffectiveAt  json.RawMessage `json:"last_effective_at,omitempty"`
			LifecycleVersion json.RawMessage `json:"lifecycle_version,omitempty"`
		} `json:"pipeline"`
		Modules map[string]struct {
			Status            string             `json:"status"`
			RunId             json.RawMessage    `json:"run_id,omitempty"`
			RunRef            json.RawMessage    `json:"run_ref,omitempty"`
			WorkId            json.RawMessage    `json:"work_id,omitempty"`
			ModuleId          json.RawMessage    `json:"module_id,omitempty"`
			GateId            json.RawMessage    `json:"gate_id,omitempty"`
			GateType          json.RawMessage    `json:"gate_type,omitempty"`
			Title             json.RawMessage    `json:"title,omitempty"`
			ModuleDir         json.RawMessage    `json:"module_dir,omitempty"`
			Attempt           json.RawMessage    `json:"attempt,omitempty"`
			CurrentAttempt    json.RawMessage    `json:"current_attempt,omitempty"`
			PreviousState     json.RawMessage    `json:"previous_state,omitempty"`
			ReasonCode        json.RawMessage    `json:"reason_code,omitempty"`
			HaltReason        json.RawMessage    `json:"halt_reason,omitempty"`
			TerminalStatus    json.RawMessage    `json:"terminal_status,omitempty"`
			TerminalDecision  json.RawMessage    `json:"terminal_decision,omitempty"`
			RunMode           json.RawMessage    `json:"run_mode,omitempty"`
			Resume            json.RawMessage    `json:"resume,omitempty"`
			RequestedModuleId json.RawMessage    `json:"requested_module_id,omitempty"`
			Entrypoint        json.RawMessage    `json:"entrypoint,omitempty"`
			CurrentPhase      json.RawMessage    `json:"current_phase,omitempty"`
			StartedAt         json.RawMessage    `json:"started_at,omitempty"`
			AttemptStartedAt  json.RawMessage    `json:"attempt_started_at,omitempty"`
			PhaseStartedAt    json.RawMessage    `json:"phase_started_at,omitempty"`
			CompletedAt       json.RawMessage    `json:"completed_at,omitempty"`
			CompletionSummary json.RawMessage    `json:"completion_summary,omitempty"`
			FailCount         json.RawMessage    `json:"fail_count,omitempty"`
			FailSummaries     *[]json.RawMessage `json:"fail_summaries,omitempty"`
			LastFailure       json.RawMessage    `json:"last_failure,omitempty"`
			BlockedAt         json.RawMessage    `json:"blocked_at,omitempty"`
			BlockedReason     json.RawMessage    `json:"blocked_reason,omitempty"`
			BlockedPhase      json.RawMessage    `json:"blocked_phase,omitempty"`
			BlockedFailCount  json.RawMessage    `json:"blocked_fail_count,omitempty"`
			DispatchId        json.RawMessage    `json:"dispatch_id,omitempty"`
			GatewayLabel      json.RawMessage    `json:"gateway_label,omitempty"`
			SessionId         json.RawMessage    `json:"session_id,omitempty"`
			SessionKey        json.RawMessage    `json:"session_key,omitempty"`
			Model             json.RawMessage    `json:"model,omitempty"`
			CommitHash        json.RawMessage    `json:"commit_hash,omitempty"`
			History           *[]struct {
				Timestamp *string         `json:"timestamp,omitempty"`
				From      json.RawMessage `json:"from,omitempty"`
				To        json.RawMessage `json:"to,omitempty"`
				Agent     json.RawMessage `json:"agent,omitempty"`
				Note      json.RawMessage `json:"note,omitempty"`
			} `json:"history,omitempty"`
			Validation       json.RawMessage `json:"validation,omitempty"`
			ProjectionSource json.RawMessage `json:"projection_source,omitempty"`
			LatestEventType  json.RawMessage `json:"latest_event_type,omitempty"`
			LatestEventAt    json.RawMessage `json:"latest_event_at,omitempty"`
			LastEventId      json.RawMessage `json:"last_event_id,omitempty"`
			LastEffectiveAt  json.RawMessage `json:"last_effective_at,omitempty"`
			LifecycleVersion json.RawMessage `json:"lifecycle_version,omitempty"`
		} `json:"modules"`
		Gates map[string]struct {
			Status            string             `json:"status"`
			RunId             json.RawMessage    `json:"run_id,omitempty"`
			RunRef            json.RawMessage    `json:"run_ref,omitempty"`
			WorkId            json.RawMessage    `json:"work_id,omitempty"`
			ModuleId          json.RawMessage    `json:"module_id,omitempty"`
			GateId            json.RawMessage    `json:"gate_id,omitempty"`
			GateType          json.RawMessage    `json:"gate_type,omitempty"`
			Title             json.RawMessage    `json:"title,omitempty"`
			ModuleDir         json.RawMessage    `json:"module_dir,omitempty"`
			Attempt           json.RawMessage    `json:"attempt,omitempty"`
			CurrentAttempt    json.RawMessage    `json:"current_attempt,omitempty"`
			PreviousState     json.RawMessage    `json:"previous_state,omitempty"`
			ReasonCode        json.RawMessage    `json:"reason_code,omitempty"`
			HaltReason        json.RawMessage    `json:"halt_reason,omitempty"`
			TerminalStatus    json.RawMessage    `json:"terminal_status,omitempty"`
			TerminalDecision  json.RawMessage    `json:"terminal_decision,omitempty"`
			RunMode           json.RawMessage    `json:"run_mode,omitempty"`
			Resume            json.RawMessage    `json:"resume,omitempty"`
			RequestedModuleId json.RawMessage    `json:"requested_module_id,omitempty"`
			Entrypoint        json.RawMessage    `json:"entrypoint,omitempty"`
			CurrentPhase      json.RawMessage    `json:"current_phase,omitempty"`
			StartedAt         json.RawMessage    `json:"started_at,omitempty"`
			AttemptStartedAt  json.RawMessage    `json:"attempt_started_at,omitempty"`
			PhaseStartedAt    json.RawMessage    `json:"phase_started_at,omitempty"`
			CompletedAt       json.RawMessage    `json:"completed_at,omitempty"`
			CompletionSummary json.RawMessage    `json:"completion_summary,omitempty"`
			FailCount         json.RawMessage    `json:"fail_count,omitempty"`
			FailSummaries     *[]json.RawMessage `json:"fail_summaries,omitempty"`
			LastFailure       json.RawMessage    `json:"last_failure,omitempty"`
			BlockedAt         json.RawMessage    `json:"blocked_at,omitempty"`
			BlockedReason     json.RawMessage    `json:"blocked_reason,omitempty"`
			BlockedPhase      json.RawMessage    `json:"blocked_phase,omitempty"`
			BlockedFailCount  json.RawMessage    `json:"blocked_fail_count,omitempty"`
			DispatchId        json.RawMessage    `json:"dispatch_id,omitempty"`
			GatewayLabel      json.RawMessage    `json:"gateway_label,omitempty"`
			SessionId         json.RawMessage    `json:"session_id,omitempty"`
			SessionKey        json.RawMessage    `json:"session_key,omitempty"`
			Model             json.RawMessage    `json:"model,omitempty"`
			CommitHash        json.RawMessage    `json:"commit_hash,omitempty"`
			History           *[]struct {
				Timestamp *string         `json:"timestamp,omitempty"`
				From      json.RawMessage `json:"from,omitempty"`
				To        json.RawMessage `json:"to,omitempty"`
				Agent     json.RawMessage `json:"agent,omitempty"`
				Note      json.RawMessage `json:"note,omitempty"`
			} `json:"history,omitempty"`
			Validation       json.RawMessage `json:"validation,omitempty"`
			ProjectionSource json.RawMessage `json:"projection_source,omitempty"`
			LatestEventType  json.RawMessage `json:"latest_event_type,omitempty"`
			LatestEventAt    json.RawMessage `json:"latest_event_at,omitempty"`
			LastEventId      json.RawMessage `json:"last_event_id,omitempty"`
			LastEffectiveAt  json.RawMessage `json:"last_effective_at,omitempty"`
			LifecycleVersion json.RawMessage `json:"lifecycle_version,omitempty"`
		} `json:"gates"`
		Generators *map[string]struct {
			Status            string             `json:"status"`
			RunId             json.RawMessage    `json:"run_id,omitempty"`
			RunRef            json.RawMessage    `json:"run_ref,omitempty"`
			WorkId            json.RawMessage    `json:"work_id,omitempty"`
			ModuleId          json.RawMessage    `json:"module_id,omitempty"`
			GateId            json.RawMessage    `json:"gate_id,omitempty"`
			GateType          json.RawMessage    `json:"gate_type,omitempty"`
			Title             json.RawMessage    `json:"title,omitempty"`
			ModuleDir         json.RawMessage    `json:"module_dir,omitempty"`
			Attempt           json.RawMessage    `json:"attempt,omitempty"`
			CurrentAttempt    json.RawMessage    `json:"current_attempt,omitempty"`
			PreviousState     json.RawMessage    `json:"previous_state,omitempty"`
			ReasonCode        json.RawMessage    `json:"reason_code,omitempty"`
			HaltReason        json.RawMessage    `json:"halt_reason,omitempty"`
			TerminalStatus    json.RawMessage    `json:"terminal_status,omitempty"`
			TerminalDecision  json.RawMessage    `json:"terminal_decision,omitempty"`
			RunMode           json.RawMessage    `json:"run_mode,omitempty"`
			Resume            json.RawMessage    `json:"resume,omitempty"`
			RequestedModuleId json.RawMessage    `json:"requested_module_id,omitempty"`
			Entrypoint        json.RawMessage    `json:"entrypoint,omitempty"`
			CurrentPhase      json.RawMessage    `json:"current_phase,omitempty"`
			StartedAt         json.RawMessage    `json:"started_at,omitempty"`
			AttemptStartedAt  json.RawMessage    `json:"attempt_started_at,omitempty"`
			PhaseStartedAt    json.RawMessage    `json:"phase_started_at,omitempty"`
			CompletedAt       json.RawMessage    `json:"completed_at,omitempty"`
			CompletionSummary json.RawMessage    `json:"completion_summary,omitempty"`
			FailCount         json.RawMessage    `json:"fail_count,omitempty"`
			FailSummaries     *[]json.RawMessage `json:"fail_summaries,omitempty"`
			LastFailure       json.RawMessage    `json:"last_failure,omitempty"`
			BlockedAt         json.RawMessage    `json:"blocked_at,omitempty"`
			BlockedReason     json.RawMessage    `json:"blocked_reason,omitempty"`
			BlockedPhase      json.RawMessage    `json:"blocked_phase,omitempty"`
			BlockedFailCount  json.RawMessage    `json:"blocked_fail_count,omitempty"`
			DispatchId        json.RawMessage    `json:"dispatch_id,omitempty"`
			GatewayLabel      json.RawMessage    `json:"gateway_label,omitempty"`
			SessionId         json.RawMessage    `json:"session_id,omitempty"`
			SessionKey        json.RawMessage    `json:"session_key,omitempty"`
			Model             json.RawMessage    `json:"model,omitempty"`
			CommitHash        json.RawMessage    `json:"commit_hash,omitempty"`
			History           *[]struct {
				Timestamp *string         `json:"timestamp,omitempty"`
				From      json.RawMessage `json:"from,omitempty"`
				To        json.RawMessage `json:"to,omitempty"`
				Agent     json.RawMessage `json:"agent,omitempty"`
				Note      json.RawMessage `json:"note,omitempty"`
			} `json:"history,omitempty"`
			Validation       json.RawMessage `json:"validation,omitempty"`
			ProjectionSource json.RawMessage `json:"projection_source,omitempty"`
			LatestEventType  json.RawMessage `json:"latest_event_type,omitempty"`
			LatestEventAt    json.RawMessage `json:"latest_event_at,omitempty"`
			LastEventId      json.RawMessage `json:"last_event_id,omitempty"`
			LastEffectiveAt  json.RawMessage `json:"last_effective_at,omitempty"`
			LifecycleVersion json.RawMessage `json:"lifecycle_version,omitempty"`
		} `json:"generators,omitempty"`
		Validators *map[string]struct {
			Status            string             `json:"status"`
			RunId             json.RawMessage    `json:"run_id,omitempty"`
			RunRef            json.RawMessage    `json:"run_ref,omitempty"`
			WorkId            json.RawMessage    `json:"work_id,omitempty"`
			ModuleId          json.RawMessage    `json:"module_id,omitempty"`
			GateId            json.RawMessage    `json:"gate_id,omitempty"`
			GateType          json.RawMessage    `json:"gate_type,omitempty"`
			Title             json.RawMessage    `json:"title,omitempty"`
			ModuleDir         json.RawMessage    `json:"module_dir,omitempty"`
			Attempt           json.RawMessage    `json:"attempt,omitempty"`
			CurrentAttempt    json.RawMessage    `json:"current_attempt,omitempty"`
			PreviousState     json.RawMessage    `json:"previous_state,omitempty"`
			ReasonCode        json.RawMessage    `json:"reason_code,omitempty"`
			HaltReason        json.RawMessage    `json:"halt_reason,omitempty"`
			TerminalStatus    json.RawMessage    `json:"terminal_status,omitempty"`
			TerminalDecision  json.RawMessage    `json:"terminal_decision,omitempty"`
			RunMode           json.RawMessage    `json:"run_mode,omitempty"`
			Resume            json.RawMessage    `json:"resume,omitempty"`
			RequestedModuleId json.RawMessage    `json:"requested_module_id,omitempty"`
			Entrypoint        json.RawMessage    `json:"entrypoint,omitempty"`
			CurrentPhase      json.RawMessage    `json:"current_phase,omitempty"`
			StartedAt         json.RawMessage    `json:"started_at,omitempty"`
			AttemptStartedAt  json.RawMessage    `json:"attempt_started_at,omitempty"`
			PhaseStartedAt    json.RawMessage    `json:"phase_started_at,omitempty"`
			CompletedAt       json.RawMessage    `json:"completed_at,omitempty"`
			CompletionSummary json.RawMessage    `json:"completion_summary,omitempty"`
			FailCount         json.RawMessage    `json:"fail_count,omitempty"`
			FailSummaries     *[]json.RawMessage `json:"fail_summaries,omitempty"`
			LastFailure       json.RawMessage    `json:"last_failure,omitempty"`
			BlockedAt         json.RawMessage    `json:"blocked_at,omitempty"`
			BlockedReason     json.RawMessage    `json:"blocked_reason,omitempty"`
			BlockedPhase      json.RawMessage    `json:"blocked_phase,omitempty"`
			BlockedFailCount  json.RawMessage    `json:"blocked_fail_count,omitempty"`
			DispatchId        json.RawMessage    `json:"dispatch_id,omitempty"`
			GatewayLabel      json.RawMessage    `json:"gateway_label,omitempty"`
			SessionId         json.RawMessage    `json:"session_id,omitempty"`
			SessionKey        json.RawMessage    `json:"session_key,omitempty"`
			Model             json.RawMessage    `json:"model,omitempty"`
			CommitHash        json.RawMessage    `json:"commit_hash,omitempty"`
			History           *[]struct {
				Timestamp *string         `json:"timestamp,omitempty"`
				From      json.RawMessage `json:"from,omitempty"`
				To        json.RawMessage `json:"to,omitempty"`
				Agent     json.RawMessage `json:"agent,omitempty"`
				Note      json.RawMessage `json:"note,omitempty"`
			} `json:"history,omitempty"`
			Validation       json.RawMessage `json:"validation,omitempty"`
			ProjectionSource json.RawMessage `json:"projection_source,omitempty"`
			LatestEventType  json.RawMessage `json:"latest_event_type,omitempty"`
			LatestEventAt    json.RawMessage `json:"latest_event_at,omitempty"`
			LastEventId      json.RawMessage `json:"last_event_id,omitempty"`
			LastEffectiveAt  json.RawMessage `json:"last_effective_at,omitempty"`
			LifecycleVersion json.RawMessage `json:"lifecycle_version,omitempty"`
		} `json:"validators,omitempty"`
		PipelineSteps *map[string]struct {
			Status            string             `json:"status"`
			RunId             json.RawMessage    `json:"run_id,omitempty"`
			RunRef            json.RawMessage    `json:"run_ref,omitempty"`
			WorkId            json.RawMessage    `json:"work_id,omitempty"`
			ModuleId          json.RawMessage    `json:"module_id,omitempty"`
			GateId            json.RawMessage    `json:"gate_id,omitempty"`
			GateType          json.RawMessage    `json:"gate_type,omitempty"`
			Title             json.RawMessage    `json:"title,omitempty"`
			ModuleDir         json.RawMessage    `json:"module_dir,omitempty"`
			Attempt           json.RawMessage    `json:"attempt,omitempty"`
			CurrentAttempt    json.RawMessage    `json:"current_attempt,omitempty"`
			PreviousState     json.RawMessage    `json:"previous_state,omitempty"`
			ReasonCode        json.RawMessage    `json:"reason_code,omitempty"`
			HaltReason        json.RawMessage    `json:"halt_reason,omitempty"`
			TerminalStatus    json.RawMessage    `json:"terminal_status,omitempty"`
			TerminalDecision  json.RawMessage    `json:"terminal_decision,omitempty"`
			RunMode           json.RawMessage    `json:"run_mode,omitempty"`
			Resume            json.RawMessage    `json:"resume,omitempty"`
			RequestedModuleId json.RawMessage    `json:"requested_module_id,omitempty"`
			Entrypoint        json.RawMessage    `json:"entrypoint,omitempty"`
			CurrentPhase      json.RawMessage    `json:"current_phase,omitempty"`
			StartedAt         json.RawMessage    `json:"started_at,omitempty"`
			AttemptStartedAt  json.RawMessage    `json:"attempt_started_at,omitempty"`
			PhaseStartedAt    json.RawMessage    `json:"phase_started_at,omitempty"`
			CompletedAt       json.RawMessage    `json:"completed_at,omitempty"`
			CompletionSummary json.RawMessage    `json:"completion_summary,omitempty"`
			FailCount         json.RawMessage    `json:"fail_count,omitempty"`
			FailSummaries     *[]json.RawMessage `json:"fail_summaries,omitempty"`
			LastFailure       json.RawMessage    `json:"last_failure,omitempty"`
			BlockedAt         json.RawMessage    `json:"blocked_at,omitempty"`
			BlockedReason     json.RawMessage    `json:"blocked_reason,omitempty"`
			BlockedPhase      json.RawMessage    `json:"blocked_phase,omitempty"`
			BlockedFailCount  json.RawMessage    `json:"blocked_fail_count,omitempty"`
			DispatchId        json.RawMessage    `json:"dispatch_id,omitempty"`
			GatewayLabel      json.RawMessage    `json:"gateway_label,omitempty"`
			SessionId         json.RawMessage    `json:"session_id,omitempty"`
			SessionKey        json.RawMessage    `json:"session_key,omitempty"`
			Model             json.RawMessage    `json:"model,omitempty"`
			CommitHash        json.RawMessage    `json:"commit_hash,omitempty"`
			History           *[]struct {
				Timestamp *string         `json:"timestamp,omitempty"`
				From      json.RawMessage `json:"from,omitempty"`
				To        json.RawMessage `json:"to,omitempty"`
				Agent     json.RawMessage `json:"agent,omitempty"`
				Note      json.RawMessage `json:"note,omitempty"`
			} `json:"history,omitempty"`
			Validation       json.RawMessage `json:"validation,omitempty"`
			ProjectionSource json.RawMessage `json:"projection_source,omitempty"`
			LatestEventType  json.RawMessage `json:"latest_event_type,omitempty"`
			LatestEventAt    json.RawMessage `json:"latest_event_at,omitempty"`
			LastEventId      json.RawMessage `json:"last_event_id,omitempty"`
			LastEffectiveAt  json.RawMessage `json:"last_effective_at,omitempty"`
			LifecycleVersion json.RawMessage `json:"lifecycle_version,omitempty"`
		} `json:"pipeline_steps,omitempty"`
		Attempts map[string]struct {
			AttemptId       string          `json:"attempt_id"`
			WorkId          string          `json:"work_id"`
			WorkType        string          `json:"work_type"`
			Attempt         json.Number     `json:"attempt"`
			Status          string          `json:"status"`
			ReasonCode      json.RawMessage `json:"reason_code,omitempty"`
			DispatchId      json.RawMessage `json:"dispatch_id,omitempty"`
			SessionId       json.RawMessage `json:"session_id,omitempty"`
			LastEventId     string          `json:"last_event_id"`
			LastEffectiveAt string          `json:"last_effective_at"`
		} `json:"attempts"`
		Progression *struct {
			ModulesTotal   json.Number `json:"modules_total"`
			ModulesPassed  json.Number `json:"modules_passed"`
			ModulesFailed  json.Number `json:"modules_failed"`
			ModulesBlocked json.Number `json:"modules_blocked"`
			ModulesActive  json.Number `json:"modules_active"`
		} `json:"progression,omitempty"`
		Waits          *map[string]json.RawMessage `json:"waits,omitempty"`
		Signals        *map[string]json.RawMessage `json:"signals,omitempty"`
		ActiveSessions *map[string]json.RawMessage `json:"active_sessions,omitempty"`
		Cooldowns      *map[string]json.RawMessage `json:"cooldowns,omitempty"`
		GeneratedAt    *string                     `json:"generated_at,omitempty"`
		LastEventId    json.RawMessage             `json:"last_event_id,omitempty"`
		LastEventType  json.RawMessage             `json:"last_event_type,omitempty"`
		EventCount     *json.Number                `json:"event_count,omitempty"`
	} `json:"lifecycle_projection"`
	ScenarioFacts []struct {
		ScenarioId      string          `json:"scenario_id"`
		Provenance      string          `json:"provenance"`
		Status          string          `json:"status"`
		EventTypes      []string        `json:"event_types"`
		ReasonCode      json.RawMessage `json:"reason_code,omitempty"`
		BundleReference json.RawMessage `json:"bundle_reference,omitempty"`
	} `json:"scenario_facts"`
	Capabilities []struct {
		Capability string          `json:"capability"`
		Status     string          `json:"status"`
		ReasonCode *string         `json:"reason_code"`
		Details    json.RawMessage `json:"details,omitempty"`
	} `json:"capabilities"`
}

type ComposedPromptV1 struct {
	Extensions      json.RawMessage   `json:"extensions,omitempty"`
	SchemaVersion   string            `json:"schema_version"`
	ArtifactId      string            `json:"artifact_id"`
	Reference       string            `json:"reference"`
	TemplateVersion string            `json:"template_version"`
	Sections        []json.RawMessage `json:"sections"`
	Model           json.RawMessage   `json:"model,omitempty"`
	Provider        json.RawMessage   `json:"provider,omitempty"`
	Thinking        json.RawMessage   `json:"thinking,omitempty"`
	Completeness    string            `json:"completeness"`
	ByteLength      json.Number       `json:"byte_length"`
	Sha256          string            `json:"sha256"`
	Correlation     struct {
		AgentId         json.RawMessage `json:"agent_id,omitempty"`
		ModuleId        json.RawMessage `json:"module_id,omitempty"`
		GateType        json.RawMessage `json:"gate_type,omitempty"`
		ParentSessionId json.RawMessage `json:"parent_session_id,omitempty"`
		TraceId         json.RawMessage `json:"trace_id,omitempty"`
		SpanId          json.RawMessage `json:"span_id,omitempty"`
		ParentSpanId    json.RawMessage `json:"parent_span_id,omitempty"`
		Attempt         json.RawMessage `json:"attempt,omitempty"`
		DispatchId      json.RawMessage `json:"dispatch_id,omitempty"`
		GateId          json.RawMessage `json:"gate_id,omitempty"`
		ModelCallId     json.RawMessage `json:"model_call_id,omitempty"`
		Producer        string          `json:"producer"`
		Project         string          `json:"project"`
		RunId           string          `json:"run_id"`
		SessionId       json.RawMessage `json:"session_id,omitempty"`
		Source          string          `json:"source"`
		ToolCallId      json.RawMessage `json:"tool_call_id,omitempty"`
		WorkId          json.RawMessage `json:"work_id,omitempty"`
		WorkType        json.RawMessage `json:"work_type,omitempty"`
	} `json:"correlation"`
}

type PipelineCommandRequestV1 struct {
	Extensions               json.RawMessage `json:"extensions,omitempty"`
	SchemaVersion            string          `json:"schema_version"`
	CommandId                string          `json:"command_id"`
	CommandType              string          `json:"command_type"`
	Project                  string          `json:"project"`
	RunId                    string          `json:"run_id"`
	Actor                    string          `json:"actor"`
	Capability               string          `json:"capability"`
	IssuedAt                 string          `json:"issued_at"`
	ExpiresAt                string          `json:"expires_at"`
	Reason                   string          `json:"reason"`
	Target                   json.RawMessage `json:"target"`
	ExpectedLifecycleVersion json.Number     `json:"expected_lifecycle_version"`
	Decision                 json.RawMessage `json:"decision,omitempty"`
}
