// Code generated by scripts/generate-telemetry-contracts.mjs. DO NOT EDIT.
package telemetryv1

import "encoding/json"

type CorrelationIdentity struct {
 Project string `json:"project"`; RunID string `json:"run_id"`; WorkID *string `json:"work_id,omitempty"`; WorkType *string `json:"work_type,omitempty"`; GateID *string `json:"gate_id,omitempty"`; Attempt *int `json:"attempt,omitempty"`; DispatchID *string `json:"dispatch_id,omitempty"`; SessionID *string `json:"session_id,omitempty"`; AgentID *string `json:"agent_id,omitempty"`; ModelCallID *string `json:"model_call_id,omitempty"`; ToolCallID *string `json:"tool_call_id,omitempty"`; Source string `json:"source"`; Producer string `json:"producer"`
}
type Envelope struct { CorrelationIdentity; SchemaVersion string `json:"schema_version"`; EventID string `json:"event_id"`; Type string `json:"type"`; OccurredAt string `json:"occurred_at"`; EmittedAt string `json:"emitted_at"`; Seq uint64 `json:"seq"`; Cursor *string `json:"cursor,omitempty"`; CausationID *string `json:"causation_id,omitempty"`; Extensions map[string]json.RawMessage `json:"extensions,omitempty"` }
