import { canonicalJson } from './canonical-json.ts';
export { canonicalJson } from './canonical-json.ts';
import crypto from 'node:crypto';
import fs from 'node:fs';
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import type { ContractValidationResult, ObservabilityCompletenessV1, ObservabilityDefinition, ProducerClosureV1, ProducerGapReportV1, ProducerRecordV1, ReplayRangeV1 } from './types.ts';

type Validator=((value:unknown)=>boolean)&{errors?:unknown[]|null};
interface AjvInstance { addSchema(schema:object):void; compile(schema:object):Validator }
const schema=JSON.parse(fs.readFileSync(new URL('../schemas/pipeline-observability.v1.schema.json',import.meta.url),'utf8')) as {$id:string};
const AjvConstructor=Ajv2020 as unknown as new(options:{allErrors:boolean;strict:boolean})=>AjvInstance;
const installFormats=addFormats as unknown as(instance:AjvInstance)=>AjvInstance;
const ajv=new AjvConstructor({allErrors:true,strict:true}); installFormats(ajv); ajv.addSchema(schema);
const validators=new Map<string,Validator>();
export function contentDigest(value:unknown):string { return `sha256:${crypto.createHash('sha256').update(canonicalJson(value)).digest('hex')}`; }
export function producerRecordDigest(record:Omit<ProducerRecordV1,'recordDigest'>|ProducerRecordV1):string { const {recordDigest:_,...unsigned}=record as ProducerRecordV1;return contentDigest(unsigned); }
export function producerClosureDigest(closure:Omit<ProducerClosureV1,'closureDigest'>|ProducerClosureV1):string { const {closureDigest:_,...unsigned}=closure as ProducerClosureV1;return contentDigest(unsigned); }
function errors(value:unknown[]|null|undefined):string[]{return value?.map((item)=>{const error=item as {instancePath?:string;message?:string};return `${error.instancePath||'/'} ${error.message||'is invalid'}`;})??['validation failed'];}
function relations(definition:ObservabilityDefinition,value:unknown):string[]{
  if(definition==='producerRecord'){const record=value as ProducerRecordV1;return producerRecordDigest(record)===record.recordDigest?[]:['/recordDigest does not match the immutable record'];}
  if(definition==='replayRange'){const range=value as ReplayRangeV1;return range.toSequence>=range.fromSequence?[]:['/toSequence must not be before /fromSequence'];}
  if(definition==='gapReport'){const gap=value as ProducerGapReportV1;return gap.toSequence>=gap.fromSequence?[]:['/toSequence must not be before /fromSequence'];}
  if(definition==='producerClosure'){const closure=value as ProducerClosureV1;const rangeOk=closure.recordCount===0?(closure.firstSequence===0&&closure.finalSequence===0):(closure.firstSequence===1&&closure.finalSequence>=closure.firstSequence&&closure.recordCount===closure.finalSequence);const result:string[]=[];if(!rangeOk)result.push('/recordCount must describe a run sequence interval that starts at one');if(producerClosureDigest(closure)!==closure.closureDigest)result.push('/closureDigest does not match the immutable closure');return result;}
  if(definition==='observabilityCompleteness'){const completeness=value as ObservabilityCompletenessV1;const result:string[]=[];const required=new Set(completeness.requiredClosureIds);const admitted=new Set(completeness.admittedClosureIds);const missing=new Set(completeness.missingClosureIds);if(completeness.admittedClosureIds.some((id)=>!required.has(id))||completeness.missingClosureIds.some((id)=>!required.has(id)))result.push('/admittedClosureIds and /missingClosureIds must be subsets of /requiredClosureIds');if(completeness.requiredClosureIds.some((id)=>(admitted.has(id)?1:0)+(missing.has(id)?1:0)!==1))result.push('/requiredClosureIds must be partitioned between admitted and missing closures');const itemIds=new Set(completeness.unresolvedItems.map((item)=>item.itemId));if(itemIds.size!==completeness.unresolvedItems.length)result.push('/unresolvedItems must use unique itemId values');if(completeness.missingClosureIds.some((id)=>!completeness.unresolvedItems.some((item)=>item.kind==='missing-closure'&&item.subjectId===id)))result.push('/missingClosureIds require an attributed missing-closure item');if(completeness.missingRanges.some((gap)=>gap.pipelineRunId!==completeness.pipelineRunId))result.push('/missingRanges must belong to /pipelineRunId');if(completeness.missingRanges.some((gap)=>gap.toSequence<gap.fromSequence))result.push('/missingRanges must use ordered sequence ranges');if(completeness.missingRanges.some((gap)=>gap.state==='restored'))result.push('/missingRanges can contain only unresolved missing or unavailable ranges');const hasCause=completeness.missingClosureIds.length>0||completeness.missingRanges.length>0||completeness.unresolvedItems.length>0;if(completeness.state==='complete'&&hasCause)result.push('/state complete requires all closures and no unresolved observability items');if(completeness.state!=='complete'&&!hasCause)result.push('/state partial, degraded, or unknown requires an attributed observability cause');return result;}
  return [];
}
export function checkPipelineObservabilityContract(definition:ObservabilityDefinition,value:unknown):ContractValidationResult{let validate=validators.get(definition);if(!validate){validate=ajv.compile({$ref:`${schema.$id}#/$defs/${definition}`}) as Validator;validators.set(definition,validate);}if(!validate(value))return{ok:false,errors:errors(validate.errors)};const relationErrors=relations(definition,value);return{ok:relationErrors.length===0,errors:relationErrors};}
export function validatePipelineObservabilityContract(definition:ObservabilityDefinition,value:unknown):void{const result=checkPipelineObservabilityContract(definition,value);if(!result.ok)throw new Error(`OBSERVABILITY_CONTRACT_INVALID:${definition}:${result.errors.join(';')}`);}
export function decodePipelineObservabilityContract(definition:ObservabilityDefinition,raw:Uint8Array|string):unknown{if(raw instanceof Uint8Array&&raw.length>=3&&raw[0]===0xef&&raw[1]===0xbb&&raw[2]===0xbf)throw new Error('OBSERVABILITY_WIRE_BOM_FORBIDDEN');const text=typeof raw==='string'?raw:new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(raw);const value=JSON.parse(text) as unknown;if(canonicalJson(value)!==text)throw new Error('OBSERVABILITY_WIRE_NOT_RFC8785_CANONICAL');validatePipelineObservabilityContract(definition,value);return value;}
