import fs from 'node:fs';
import path from 'node:path';
import type { NativeWorkerPoolLimits } from './native-resource-pool.ts';

export interface NativeWorkerPoolPolicy {
  readonly schemaVersion: 1;
  readonly role: string;
  readonly nodeName: string;
  readonly policyDigest: string;
  readonly cgroupRoot: string;
  readonly ownershipRoot: string;
  readonly nodeIdentityFile: string;
  readonly maximumActiveScopes: number;
  readonly limits: NativeWorkerPoolLimits;
}

/** Generated by host preparation; no envelope or mutable worker environment defines aggregate capacity. */
export function readNativeWorkerPoolPolicy(file: string, role: string): NativeWorkerPoolPolicy {
  if (!path.isAbsolute(file)) throw new Error('WORKER_NATIVE_POOL_POLICY_PATH_REQUIRED');
  const fd = fs.openSync(file, fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW | fs.constants.O_NONBLOCK);
  try {
    const stat = fs.fstatSync(fd);
    if (!stat.isFile() || stat.uid !== 0 || (stat.mode & 0o022) !== 0 || stat.size < 1 || stat.size > 65536) {
      throw new Error('WORKER_NATIVE_POOL_POLICY_NOT_TRUSTED');
    }
    const value = JSON.parse(fs.readFileSync(fd, 'utf8')) as NativeWorkerPoolPolicy;
    validate(value, role);
    return Object.freeze({ ...value, limits: Object.freeze({ ...value.limits }) });
  } finally { fs.closeSync(fd); }
}

function validate(value: NativeWorkerPoolPolicy, role: string): void {
  if (value?.schemaVersion !== 1 || value.role !== role || typeof value.nodeName !== 'string' || !value.nodeName
    || typeof value.policyDigest !== 'string' || !/^[a-f0-9]{64}$/u.test(value.policyDigest)) throw new Error('WORKER_NATIVE_POOL_POLICY_INVALID');
  validatePaths(value);
  validateLimits(value);
}

function validatePaths(value: NativeWorkerPoolPolicy): void {
  for (const location of [value.cgroupRoot, value.ownershipRoot, value.nodeIdentityFile]) {
    if (typeof location !== 'string' || !path.isAbsolute(location) || location === '/' || path.resolve(location) !== location) {
      throw new Error('WORKER_NATIVE_POOL_POLICY_PATH_INVALID');
    }
  }
}

function validateLimits(value: NativeWorkerPoolPolicy): void {
  for (const number of [value.maximumActiveScopes, value.limits?.memoryBytes, value.limits?.tasks,
    value.limits?.cpuQuotaMicroseconds, value.limits?.cpuPeriodMicroseconds]) {
    if (!Number.isSafeInteger(number) || number < 1) throw new Error('WORKER_NATIVE_POOL_POLICY_LIMIT_INVALID');
  }
}
