{{- if .Values.rbac.execNamespaces }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-kubeconfig
data:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: in-cluster
        cluster:
          server: https://kubernetes.default.svc
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    users:
      - name: ops
        user:
          tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    contexts:
      - name: ops
        context:
          cluster: in-cluster
          user: ops
          namespace: {{ .Values.defaultNamespace | quote }}
    current-context: ops
{{- end }}
