apiVersion: v1
kind: ServiceAccount
metadata: {name: {{ .Release.Name }}}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: {name: {{ .Release.Namespace }}-{{ .Release.Name }}-reader}
rules:
  - apiGroups: [""]
    resources: [pods, pods/log, services, events, persistentvolumeclaims]
    verbs: [get, list]
  - apiGroups: [apps]
    resources: [deployments, statefulsets, daemonsets, replicasets]
    verbs: [get, list]
  - apiGroups: [batch]
    resources: [jobs, cronjobs]
    verbs: [get, list]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses, networkpolicies]
    verbs: [get, list]
  - apiGroups: [cilium.io]
    resources: [ciliumnetworkpolicies]
    verbs: [get, list]
  - apiGroups: [argoproj.io]
    resources: [applications]
    verbs: [get, list]
{{- range .Values.rbac.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Release.Namespace }}-{{ $.Release.Name }}-reader
  namespace: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $.Release.Namespace }}-{{ $.Release.Name }}-reader
subjects:
  - {kind: ServiceAccount, name: {{ $.Release.Name }}, namespace: {{ $.Release.Namespace }}}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: {name: {{ .Release.Namespace }}-{{ .Release.Name }}-cluster-reader}
rules:
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, list]
  - apiGroups: [cilium.io]
    resources: [ciliumclusterwidenetworkpolicies]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: {name: {{ .Release.Namespace }}-{{ .Release.Name }}-cluster-reader}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-cluster-reader
subjects:
  - {kind: ServiceAccount, name: {{ .Release.Name }}, namespace: {{ .Release.Namespace }}}
