export const productOperatorPage = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Demo acceptance</title><style>body{font:16px system-ui;max-width:60rem;margin:3rem auto;padding:1rem}button,input,select,textarea{font:inherit;margin:.4rem;padding:.5rem}pre{white-space:pre-wrap}label{display:block}</style><h1>Demo acceptance</h1><p>Sign in through the configured Tailscale ingress. Decisions require an explicitly authorized operator. Acceptance records the current demo; extension changes its deadline.</p><button id="signin">Sign in / refresh session</button><button id="refresh">Refresh demos</button><button id="history">My decision history</button><label>Ready demo <select id="subject"></select></label><pre id="details"></pre><label>Decision <select id="action"><option value="accept">Accept</option><option value="extend">Extend</option></select></label><label>Extension in seconds <input id="seconds" type="number" min="1" value="3600"></label><label>Reason <textarea id="reason" maxlength="2000"></textarea></label><button id="decide">Record decision</button><h2>Recovery</h2><p>Keep the decision ID until a confirmed receipt appears. Recovery reuses the original signed decision.</p><label>Decision ID <input id="decision"></label><button id="recover">Recover decision</button><button id="retry">Retry original submission</button><button id="leave">Leave unresolved in history</button><pre id="result" role="status"></pre><script>
const el=id=>document.getElementById(id);let subjects=[];let pending=localStorage.getItem('prism-product-pending')||'';el('decision').value=pending;
const csrf=()=>decodeURIComponent((document.cookie.split('; ').find(v=>v.startsWith('prism_csrf='))||'').slice(11));
async function api(path,body){const response=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json','x-prism-csrf':csrf()},...(body===undefined?{}:{body:JSON.stringify(body)})});const result=await response.json();if(!response.ok)throw Error(result.error||'Request rejected');return result;}
async function show(operation){try{const result=await operation();el('result').textContent=JSON.stringify(result,null,2);if(result.state==='applied'&&result.decisionId===pending){localStorage.removeItem('prism-product-pending');localStorage.removeItem('prism-product-intent');pending='';}return result;}catch(error){el('result').textContent=error.message;}}
el('history').onclick=()=>show(async()=>({durable:await api('/v1/product-decisions'),localUnresolved:JSON.parse(localStorage.getItem('prism-product-unresolved')||'[]')}));
el('signin').onclick=()=>show(()=>api('/v1/session',{}));
el('refresh').onclick=()=>show(async()=>{const data=await api('/v1/product-decisions/subjects');subjects=data.subjects;el('subject').replaceChildren(...subjects.map((s,i)=>{const option=document.createElement('option');option.value=i;option.textContent=s.runId+' — '+s.expectedExpiry;return option;}));el('subject').onchange();return {readyDemos:subjects.length};});
el('subject').onchange=()=>{el('details').textContent=JSON.stringify(subjects[Number(el('subject').value)]||{},null,2);};
el('decide').onclick=()=>show(async()=>{if(pending)throw Error('Recover the pending decision '+pending+' first.');const subject=subjects[Number(el('subject').value)];if(!subject)throw Error('Refresh and select a ready demo.');if(!el('reason').value.trim())throw Error('A reason is required.');const action=el('action').value;const seconds=Number(el('seconds').value);if(new TextEncoder().encode(el('reason').value).length>2000)throw Error('Reason is too long.');if(action==='extend'&&(!Number.isSafeInteger(seconds)||seconds<1||seconds>9223372036))throw Error('Enter a valid positive extension in seconds.');const intent={decisionId:crypto.randomUUID(),action,reason:el('reason').value,subject,...(action==='extend'?{extensionSeconds:Number(el('seconds').value)}:{})};localStorage.setItem('prism-product-intent',JSON.stringify(intent));pending=intent.decisionId;localStorage.setItem('prism-product-pending',pending);el('decision').value=pending;return api('/v1/product-decisions',intent);});
el('recover').onclick=()=>show(()=>api('/v1/product-decisions/'+encodeURIComponent(el('decision').value)+'/recover',{}));
el('leave').onclick=()=>{if(!pending)return;if(!confirm('The outcome of '+pending+' is UNKNOWN. The original intent will remain in local unresolved history; a recorded decision also remains in durable history. This does not cancel or reject it. Leave it unresolved and require a fresh demo snapshot before another deliberate decision?'))return;const unresolved=JSON.parse(localStorage.getItem('prism-product-unresolved')||'[]');unresolved.push({decisionId:pending,intent:JSON.parse(localStorage.getItem('prism-product-intent')||'null')});localStorage.setItem('prism-product-unresolved',JSON.stringify(unresolved));el('result').textContent='Unresolved decision '+pending+'. Use My decision history and Recover decision to reconcile it.';localStorage.removeItem('prism-product-pending');localStorage.removeItem('prism-product-intent');pending='';subjects=[];el('subject').replaceChildren();el('details').textContent='Refresh demos before making another decision.';};
el('retry').onclick=()=>show(()=>{const id=el('decision').value;const active=JSON.parse(localStorage.getItem('prism-product-intent')||'null');const historical=JSON.parse(localStorage.getItem('prism-product-unresolved')||'[]').find(item=>item.decisionId===id);const original=active&&active.decisionId===id?active:historical&&historical.intent;if(!original)throw Error('No original intent is stored in this browser for this ID.');return api('/v1/product-decisions',original);});
</script></html>`;
