#!/usr/bin/env node
import assert from 'node:assert/strict'; import crypto from 'node:crypto'; import { execFileSync } from 'node:child_process'; import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import { buildRegistry, createProductionNovaTestGate, discoverPackages, resolveTestPlan } from '@kubeclaw/nova-core'; import { parseCapabilityProviders, resolveProviderCapability } from './provider-catalog.mjs';
const IMAGE=/^(?:[A-Za-z0-9.-]+(?::[0-9]{1,5})?\/[a-z0-9]+(?:[._\/-][a-z0-9]+)*)@(sha256:[a-f0-9]{64})$/u;
const token=process.env.BUSTER_V2_TOKEN,privateKey=process.env.BUSTER_SOURCE_ATTESTATION_PRIVATE_KEY,immutableImage=process.env.KUBECLAW_VISUAL_PREFLIGHT_IMAGE;
const repositoryRoot=path.resolve(import.meta.dirname,'../../..');const runtimeRevision=execFileSync('git',['rev-parse','HEAD'],{cwd:repositoryRoot,encoding:'utf8'}).trim();const temporary=fs.mkdtempSync(path.join(os.tmpdir(),'nova-visual-preflight-'));const fixture=path.join(temporary,'fixture'),state=path.join(temporary,'nova-state');const runId=`run:visual-preflight:${crypto.randomUUID()}`;
const git=(...args:string[])=>execFileSync('git',args,{cwd:fixture,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
const records=(relative:string)=>JSON.parse(fs.readFileSync(path.join(state,relative,'records/store.json'),'utf8')).records;
try{if(!token)throw new Error('VISUAL_PREFLIGHT_TOKEN_MISSING');if(!privateKey)throw new Error('VISUAL_PREFLIGHT_SOURCE_KEY_MISSING');const image=immutableImage?IMAGE.exec(immutableImage):null;if(!image)throw new Error('VISUAL_PREFLIGHT_IMMUTABLE_IMAGE_INVALID');const route=resolveProviderCapability(parseCapabilityProviders(),'buster','test.plan.execute');if(route.adapter!=='buster-plan-v1')throw new Error('VISUAL_PREFLIGHT_PROVIDER_UNSUPPORTED');
  fs.cpSync(path.join(repositoryRoot,'tests/verification/e2e/fixtures/nginx-project'),fixture,{recursive:true});fs.mkdirSync(path.join(fixture,'.swarm'),{recursive:true});
  const manifestPath=path.join(fixture,'k8s/deployment.yaml');fs.writeFileSync(manifestPath,fs.readFileSync(manifestPath,'utf8').replace('real-pipeline-e2e-nginx:verification',immutableImage!));
  git('init','-q','--initial-branch=main');git('config','user.name','KubeClaw Nova Preflight');git('config','user.email','nova-preflight@kubeclaw.invalid');git('add','.');git('commit','-qm','Create visual production preflight fixture');
  const pluginRoot=path.join(repositoryRoot,'skills/buster/plugins');const registry=buildRegistry(discoverPackages({installationRoots:[pluginRoot],trustPolicy:{trustedBuiltinRoots:[pluginRoot],allowedSourceDigests:new Map(),verifiedAttestations:new Map(),verifierId:'visual-production-preflight'}}));
  const declaration:any={tests:{'checked-manifest':{uses:'kubeclaw.direct-command@1',mode:'blocking',retries:0,concurrencyGroup:'manifest',config:{executable:'cp',args:['k8s/deployment.yaml','.swarm/checked-visual-preflight.yaml'],workingDirectory:'.',resultMode:'exit-code',artifacts:[{id:'checked-manifest',path:'.swarm/checked-visual-preflight.yaml',mediaType:'application/vnd.kubeclaw.checked-kubernetes-yaml'}]}},visual:{uses:'kubeclaw.visual@1',mode:'blocking',retries:0,needs:['kubernetes-deployment'],concurrencyGroup:'browser-visual',config:{manifestFile:'.swarm/visual/baselines.json',profileFile:'.swarm/browser-profiles.json',targets:['home-desktop'],comparisonProfile:'strict-v1',timeoutMs:120000},inputs:{deployment:{from:'kubernetes-deployment',output:'deployment'}}}},fixtures:{'kubernetes-deployment':{uses:'kubeclaw.kubernetes-fixture@1',retries:0,needs:['checked-manifest'],concurrencyGroup:'kubernetes-fixture',config:{image:{reference:immutableImage,digest:image[1]},serviceName:'real-pipeline-e2e-nginx',servicePort:80,namespacePrefix:'test',retention:{mode:'delete',seconds:600},readinessTimeoutSeconds:300,secretReferences:[]},inputs:{'checked-manifest':{from:'checked-manifest',output:'artifact-1',mediaType:'application/vnd.kubeclaw.checked-kubernetes-yaml'}}}},concurrencyLimits:{manifest:1,'kubernetes-fixture':1,'browser-visual':1}};
  const limits={cpuMillis:900000,memoryBytes:2147483648,logBytes:4194304,artifactBytes:67108864,artifactFiles:64,processes:64};const plan=resolveTestPlan({planId:'plan:visual:production-preflight',runId,project:'visual-production-preflight',scope:{moduleId:null,gateId:'production-preflight'},createdAt:new Date().toISOString(),declaration,suiteTemplates:[],registry,facts:{changedPaths:['k8s/deployment.yaml','.swarm/visual/baselines.json'],moduleType:'service',pipelineStage:'preflight'},policy:{defaultTimeoutMs:900000,maximumTimeoutMs:900000,defaultLimits:limits,maximumLimits:limits,maximumRetryCount:1,maximumMatrixSize:1,maximumNodes:3,defaultConcurrencyLimit:1,maximumConcurrencyLimits:{manifest:1,'kubernetes-fixture':1,'browser-visual':1}}});
  const grants=new Map<string,readonly string[]>([['checked-manifest',['command.execute']],['kubernetes-deployment',['kubernetes.fixture']],['visual',['browser.visual']]]);const nova=createProductionNovaTestGate({stateRoot:state,endpoint:route.endpoint,token,sourceAuthority:'nova:production',sourceAttestationPrivateKey:privateKey,pollMilliseconds:500,maximumResponseBytes:67108864,maximumResultBytes:67108864,maximumArchiveBytes:16777216,maximumArchiveStoreBytes:67108864,maximumEvidenceBytes:67108864,maximumEvidenceStoreBytes:134217728,recordLimits:{maximumRecords:100,maximumBytes:134217728,maximumRecordBytes:67108864}});
  const result=await nova.execute({idempotencyKey:`visual:${crypto.randomUUID()}`,pipelineStageId:'stage:visual-preflight',plan,repositoryRoot:fixture,repositoryId:'repository:visual-preflight',grants,maximumConcurrency:1,submittedAt:new Date().toISOString(),timeoutMs:1020000});assert.equal(result.remote.status.state,'completed');assert.equal(result.remote.decision.state,'passed');const imported=records('imports').find((record:any)=>record.stream==='remote-gate-imports').payload;assert.equal(imported.state,'complete');assert.equal(imported.remoteResult.cleanupErrors.length,0);const deployment=imported.remoteResult.attempts.flatMap((attempt:any)=>attempt.outputs).find((output:any)=>output.schemaId==='kubeclaw.kubernetes-deployment-fixture@1')?.value;const visual=imported.remoteResult.attempts.find((attempt:any)=>attempt.nodeId==='visual');assert.equal(visual.evidence.filter((item:any)=>item.type.startsWith('visual-')).length,3);assert.ok(deployment?.leaseName&&deployment?.namespace);
  process.stdout.write(`${JSON.stringify({ok:true,schemaVersion:'nova-visual-production-preflight.v1',suite:'visual-reg',runId,jobId:result.remote.decision.jobId,provider:route,runtimeRevision,busterRuntimeRevision:imported.remoteResult.workerRevision,fixtureRevision:git('rev-parse','HEAD'),planDigest:plan.planDigest,resultDigest:result.remote.decision.resultDigest,decisionDigest:result.remote.decision.decisionDigest,status:result.remote.status.state,decision:result.remote.decision.state,evidenceDigests:imported.evidenceDigests,evidenceImported:true,runnerCleanupVerified:true,cleanupVerified:false,clusterCleanupObserved:false,immutableImage,imageDigest:image[1],browserVersion:visual.providerDetails.values.results[0].browserVersion,resources:{leaseName:deployment.leaseName,namespace:deployment.namespace,serviceName:'real-pipeline-e2e-nginx',servicePort:80},boundary:'Nova signed source to remote Buster isolated visual provider plan',mocks:0,emulators:0},null,2)}\n`);
}finally{fs.rmSync(temporary,{recursive:true,force:true});}
