{{- if .Values.persistence.config.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubeclaw.fullname" . }}-config
  labels:
    {{- include "kubeclaw.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    {{- toYaml .Values.persistence.config.accessModes | nindent 4 }}
  {{- if .Values.persistence.config.storageClass }}
  storageClassName: {{ .Values.persistence.config.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
{{- end }}

---

{{- if .Values.persistence.workspace.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubeclaw.fullname" . }}-workspace
  labels:
    {{- include "kubeclaw.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    {{- toYaml .Values.persistence.workspace.accessModes | nindent 4 }}
  {{- if .Values.persistence.workspace.storageClass }}
  storageClassName: {{ .Values.persistence.workspace.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.workspace.size }}
{{- end }}
