apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubeclaw.fullname" . }}
  labels:
    {{- include "kubeclaw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kubeclaw.selectorLabels" . | nindent 4 }}
  ports:
    - name: gateway
      port: {{ .Values.service.gatewayPort }}
      targetPort: gateway
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") (gt (int .Values.service.nodePort) 0) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - name: bridge
      port: {{ .Values.service.bridgePort }}
      targetPort: bridge
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") (gt (int .Values.service.bridgeNodePort) 0) }}
      nodePort: {{ .Values.service.bridgeNodePort }}
      {{- end }}
  {{- if .Values.missionControl.enabled }}
    - name: dashboard
      port: 3000
      targetPort: dashboard
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") (gt (int .Values.service.dashboardNodePort) 0) }}
      nodePort: {{ .Values.service.dashboardNodePort }}
      {{- end }}
  {{- end }}
