import fs from 'node:fs';
import path from 'node:path';
import { COMMAND_TYPES, sha256, stableJson } from '../observability-contract.ts';
import { artifactPaths } from '../portable-artifacts.ts';
import { getPipelineArtifactBundle } from './artifact-bundle.ts';

const allowed=new Set(COMMAND_TYPES);
function evidenceFile(config:any){return path.join(artifactPaths({...config,pipeline_dir:getPipelineArtifactBundle(config).pipeline_dir}).root,'commands.jsonl');}
function history(config:any){try{return fs.readFileSync(evidenceFile(config),'utf8').trim().split('\n').filter(Boolean).map(JSON.parse);}catch{return[];}}
function append(config:any,state:string,command:any,reason_code:string|null=null){const record={schema_version:'pipeline_command_evidence.v1',state,recorded_at:new Date().toISOString(),command_id:command.command_id,command_type:command.command_type,actor:command.actor,target:command.target??null,expected_lifecycle_version:command.expected_lifecycle_version,reason_code,command_hash:sha256(stableJson(command))};const file=evidenceFile(config);fs.mkdirSync(path.dirname(file),{recursive:true});fs.appendFileSync(file,`${JSON.stringify(record)}\n`);return record;}
export function commandStreamKey(project:string,runId:string){if(!project||!runId)throw new Error('project and run_id are required');return`pipeline:commands:${project}:${runId}`;}
export function validateCommand(command:any,context:any){const errors=[];if(!command?.command_id)errors.push('COMMAND_ID_MISSING');if(!allowed.has(command?.command_type))errors.push('COMMAND_TYPE_UNSUPPORTED');if(!command?.actor)errors.push('ACTOR_MISSING');if(!context.capabilities?.includes(command?.capability))errors.push('CAPABILITY_DENIED');if(!command?.expires_at||Date.parse(command.expires_at)<=Date.now())errors.push('COMMAND_EXPIRED');if(!Number.isInteger(command?.expected_lifecycle_version)||command.expected_lifecycle_version!==context.lifecycle_version)errors.push('LIFECYCLE_VERSION_STALE');if(command?.target?.run_id&&command.target.run_id!==context.run_id)errors.push('TARGET_RUN_MISMATCH');if(command?.command_type==='approval.resolve'&&!['approve','reject'].includes(command?.decision))errors.push('APPROVAL_DECISION_INVALID');return{ok:errors.length===0,errors};}
export async function processCommand(config:any,command:any,context:any,handlers:any){append(config,'requested',command);const prior=history(config).filter(item=>item.command_id===command.command_id);if(prior.some(item=>item.state==='completed'))return append(config,'rejected',command,'COMMAND_DUPLICATE');const check=validateCommand(command,context);if(!check.ok)return append(config,'rejected',command,check.errors[0]);append(config,'accepted',command);const handler=handlers[command.command_type];if(typeof handler!=='function')return append(config,'rejected',command,'COMMAND_HANDLER_UNAVAILABLE');await handler(command,context);return append(config,'completed',command,null);}
export function commandControlEnabled(config:any){return config?.control?.enabled===true&&process.env.PIPELINE_CONTROL_ENABLED==='1';}
function redisFields(fields:any[]){const result:any={};for(let i=0;i<fields.length;i+=2)result[String(fields[i])]=fields[i+1];return result;}
export async function consumeCommandOnce(config:any,{redis,context,handlers,group='pipeline-authority',consumer=`nova-${process.pid}`} :any){if(!commandControlEnabled(config))return{processed:0,disabled:true};const stream=commandStreamKey(config.project,config._runId??config.run_id);try{await redis.xgroup('CREATE',stream,group,'0','MKSTREAM');}catch(error){if(!String(error).includes('BUSYGROUP'))throw error;}const result=await redis.xreadgroup('GROUP',group,consumer,'COUNT',1,'BLOCK',1000,'STREAMS',stream,'>');if(!Array.isArray(result)||!result.length)return{processed:0};const [id,fields]=result[0][1][0];const data=redisFields(fields);let command;try{command=JSON.parse(data.data);}catch{command={command_id:`invalid-${id}`,command_type:null,actor:null};append(config,'rejected',command,'COMMAND_JSON_INVALID');await redis.xack(stream,group,id);return{processed:1,rejected:true};}const evidence=await processCommand(config,command,{...context,run_id:config._runId??config.run_id},handlers);await redis.xack(stream,group,id);return{processed:1,evidence};}
