import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { artifactPaths, canonicalFingerprint, publishArtifact, verifyArtifactCatalog, writeCanonicalJson } from '../portable-artifacts.ts';
import { getPipelineArtifactBundle } from './artifact-bundle.ts';

function text(value:any){return typeof value==='string'&&value.trim()?value.trim():null;}
function json(file:string,fallback:any=null){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return fallback;}}
function lines(file:string){try{return fs.readFileSync(file,'utf8').trim().split('\n').filter(Boolean).map(JSON.parse);}catch{return[];}}
function git(repo:string,args:string[]){try{return execFileSync('git',['-C',repo,...args],{encoding:'utf8',stdio:['ignore','pipe','ignore'],timeout:10000}).trim();}catch{return null;}}
function safeConfig(config:any){const seen=new WeakSet();function visit(value:any,key=''):any{if(/secret|token|password|credential|api.?key/i.test(key))return undefined;if(value==null||['string','number','boolean'].includes(typeof value))return value;if(typeof value==='function'||typeof value==='bigint')return undefined;if(Array.isArray(value))return value.map(item=>visit(item)).filter(item=>item!==undefined);if(typeof value==='object'){if(seen.has(value))return undefined;seen.add(value);const out:any={};for(const [child,item] of Object.entries(value)){if(child.startsWith('_'))continue;const normalized=visit(item,child);if(normalized!==undefined)out[child]=normalized;}return out;}return undefined;}return visit(config??{});}
function evidenceConfig(config:any){return{...config,pipeline_dir:getPipelineArtifactBundle(config).pipeline_dir};}

export function buildRunManifest(config:any, progress:any={}){
  const repo=text(config?.repo_root); const paths=artifactPaths(evidenceConfig(config));
  const modules=Object.entries(progress?.modules??{}).map(([id,value]:any)=>({work_type:'module',work_id:id,depends_on:value?.depends_on??[],owner:'nova',configuration:value}));
  const gates=Object.entries(progress?.gates??{}).map(([id,value]:any)=>({work_type:'gate',work_id:id,depends_on:value?.depends_on??[],owner:value?.owner??'nova',configuration:value}));
  const known=new Set([...modules,...gates].map(item=>item.work_id));const steps=(progress?.execution_order??[]).filter((id:string)=>!known.has(String(id).replace(/^(gate|validator|generator|step):/,''))).map((id:string)=>{const [prefix,...rest]=String(id).split(':');return{work_type:['validator','generator'].includes(prefix)?prefix:'pipeline_step',work_id:rest.length?rest.join(':'):id,depends_on:[],owner:'nova',configuration:{execution_order_entry:id}};});
  const inputs={schema_versions:{telemetry:'telemetry_envelope.v1',lifecycle:'pipeline_lifecycle.v1',manifest:'run_manifest.v1'},project:config.project,run_id:config._runId??config.run_id,work_items:[...modules,...gates,...steps],runtime_policies:safeConfig(config),git:{repository:repo?git(repo,['config','--get','remote.origin.url']):null,branch:repo?git(repo,['branch','--show-current']):null,commit:repo?git(repo,['rev-parse','HEAD']):null,dirty:repo?Boolean(git(repo,['status','--porcelain'])):null},deployment:{image_digest:process.env.KUBECLAW_IMAGE_DIGEST??null,pod_uid:process.env.POD_UID??null,namespace:process.env.POD_NAMESPACE??null},versions:{node:process.version,pipeline:git(repo??process.cwd(),['rev-parse','HEAD'])}};
  const fingerprint=canonicalFingerprint(inputs); const manifest={schema_version:'run_manifest.v1',created_at:new Date().toISOString(),fingerprint,...inputs}; writeCanonicalJson(paths.manifest,manifest); return manifest;
}
export function writeProducerHealth(config:any, producers:any[]){const paths=artifactPaths(evidenceConfig(config));const health={schema_version:'producer_health_snapshot.v1',run_id:config._runId??config.run_id,generated_at:new Date().toISOString(),producers,completeness:producers.some(p=>['unhealthy','degraded'].includes(p.status))?'degraded':producers.some(p=>p.status==='unknown')?'partial':'complete'};writeCanonicalJson(paths.health,health);return health;}
function defaultProducerHealth(config:any,artifactCheck:any){const ingester=config?._agentObservabilityRuntime?.stats?.()??null;const events=lines(path.join(artifactPaths(evidenceConfig(config)).root,'pipeline.jsonl'));const emitted=(producer:string)=>events.filter(event=>String(event.producer??'').includes(producer)||String(event.source??'').includes(producer)).at(-1);const base={last_successful_emission:null,lag:null,checkpoint:null,invalid_count:0,quarantined_count:0,dead_letter_count:0,missing_payload_count:0,restart_count:0,reconciliation:null};const buster=emitted('buster');const namespace=emitted('namespace-controller');return[{...base,producer_id:'nova',status:artifactCheck.ok?'healthy':'degraded',last_successful_emission:new Date().toISOString(),missing_payload_count:artifactCheck.errors.length},{...base,producer_id:'openclaw-agent-observer',status:ingester?'healthy':'not_applicable',capability:ingester?null:{reason:'observer_not_enabled_for_run'}},{...base,producer_id:'agent-observability-ingester',status:ingester?(ingester.failed?'degraded':'healthy'):'not_applicable',last_successful_emission:ingester?.emitted?new Date().toISOString():null,checkpoint:ingester?String(ingester.acked):null,dead_letter_count:ingester?.deadLettered??0,missing_payload_count:ingester?.failed??0},{...base,producer_id:'buster',status:buster?'healthy':'not_applicable',last_successful_emission:buster?.emitted_at??null},{...base,producer_id:'buster-namespace-controller',status:namespace?'healthy':'not_applicable',last_successful_emission:namespace?.emitted_at??null},{...base,producer_id:'pipeline-command-authority',status:config?._commandRuntimeHealth?.status??(config?.control?.enabled?'unknown':'not_applicable'),last_successful_emission:config?._commandRuntimeHealth?.checked_at??null}];}
export function writeTerminalClosure(config:any,input:any){const paths=artifactPaths(evidenceConfig(config));const closure={schema_version:'terminal_closure.v1',run_id:config._runId??config.run_id,project:config.project,closed_at:new Date().toISOString(),outcome:input.outcome,reason_code:input.reason_code,duration_ms:input.duration_ms??null,counts:input.counts??{},cost:input.cost??null,last_work_id:input.last_work_id??null,manifest_fingerprint:input.manifest_fingerprint,observability:input.observability??'unknown',summary_reference:input.summary_reference??null,artifact_catalog_reference:'artifacts.jsonl'};writeCanonicalJson(paths.closure,closure);return closure;}
export function appendEvaluationFact(config:any,fact:any){const file=artifactPaths(evidenceConfig(config)).evaluation;fs.mkdirSync(path.dirname(file),{recursive:true});const record={schema_version:'evaluation_fact.v1',recorded_at:new Date().toISOString(),run_id:config._runId??config.run_id,...fact};fs.appendFileSync(file,`${JSON.stringify(record)}\n`);return record;}
export function publishPromptEvidence(config:any,{prompt,agent_type,work_id,attempt,model=null,provider=null,thinking=null,template_version='pipeline-prompt.v1'}:any){const sections=String(prompt).split(/(?=^#{1,6}\s+)/m).filter(Boolean).map((content,index)=>({index,title:(content.match(/^#{1,6}\s+(.+)$/m)?.[1]??`section-${index+1}`).trim(),source:index===0?'pipeline-composer':'composed-section',sha256:crypto.createHash('sha256').update(content).digest('hex'),byte_length:Buffer.byteLength(content)}));const correlation={project:config.project,run_id:config._runId??config.run_id,work_id,work_type:'module',attempt,source:'pipeline',producer:'nova/prompt-composer'};const artifact=publishArtifact(evidenceConfig(config),{logical_id:`prompt/${work_id}/${agent_type}/${attempt}`,kind:'composed-prompt',media_type:'text/markdown',bytes:prompt,producer:'nova/prompt-composer',content_class:'payload',completeness:'full',correlation});const metadata={schema_version:'composed_prompt.v1',artifact_id:artifact.artifact_id,reference:artifact.reference,template_version,sections,model,provider,thinking,completeness:'full',byte_length:artifact.byte_length,sha256:artifact.sha256,correlation};const metadataArtifact=publishArtifact(evidenceConfig(config),{logical_id:`prompt-metadata/${work_id}/${agent_type}/${attempt}`,kind:'prompt-metadata',media_type:'application/json',bytes:JSON.stringify(metadata),producer:'nova/prompt-composer',content_class:'metadata',completeness:'full',correlation});return{...metadata,metadata_reference:metadataArtifact.reference};}
export function buildArchiveManifest(config:any){const paths=artifactPaths(evidenceConfig(config));const lifecycle=path.join(paths.root,'lifecycle','canonical-events.jsonl');const telemetry=path.join(paths.root,'pipeline.jsonl');const eventLines=lines(lifecycle);const sources=[lifecycle,telemetry,paths.catalog,paths.manifest,paths.closure,paths.health,paths.evaluation].filter(f=>fs.existsSync(f)).map(file=>{const bytes=fs.readFileSync(file);return{reference:path.relative(paths.root,file).split(path.sep).join('/'),byte_length:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')}});const closure=json(paths.closure,{});const archive={schema_version:'run_archive_manifest.v1',run_id:config._runId??config.run_id,project:config.project,created_at:new Date().toISOString(),lifecycle:{event_count:eventLines.length,first_cursor:eventLines[0]?.event_id??null,last_cursor:eventLines.at(-1)?.event_id??null},sources,manifest_reference:'run-manifest.json',terminal_reference:fs.existsSync(paths.closure)?'terminal-closure.json':null,completeness:closure.observability??'unknown',repair_state:'verified'};const hash=canonicalFingerprint(archive);const result={...archive,sha256:hash};writeCanonicalJson(paths.archive,result);return result;}
export function appendRunCatalog(config:any,archive:any){const paths=artifactPaths(evidenceConfig(config));const catalog=path.join(path.dirname(path.dirname(paths.root)),'run-catalog.jsonl');const existing=lines(catalog);if(existing.some(item=>item.run_id===archive.run_id&&item.sha256===archive.sha256))return archive;fs.mkdirSync(path.dirname(catalog),{recursive:true});fs.appendFileSync(catalog,`${JSON.stringify({run_id:archive.run_id,project:archive.project,archive_reference:path.relative(path.dirname(catalog),paths.archive).split(path.sep).join('/'),sha256:archive.sha256,completeness:archive.completeness,repair_state:archive.repair_state,recorded_at:new Date().toISOString()})}\n`);return archive;}
export function finalizeEvidencePlane(config:any,input:any){const normalized=evidenceConfig(config);const manifest=fs.existsSync(artifactPaths(normalized).manifest)?json(artifactPaths(normalized).manifest):buildRunManifest(config,input.progress);const artifactCheck=verifyArtifactCatalog(normalized);const health=writeProducerHealth(config,input.producers??defaultProducerHealth(config,artifactCheck));const closure=writeTerminalClosure(config,{...input,manifest_fingerprint:manifest.fingerprint,observability:health.completeness});const archive=buildArchiveManifest(config);appendRunCatalog(config,archive);return{manifest,health,closure,archive,artifact_check:artifactCheck};}
export function finalizeSummaryEvidence(config:any,{progress,terminalStatus,reasonCode,durationSeconds,runStats,cost,summaryReference}:any){return finalizeEvidencePlane(config,{progress,outcome:terminalStatus==='succeeded'?'success':terminalStatus==='paused'?'paused':terminalStatus==='cancelled'?'cancelled':'failure',reason_code:reasonCode,duration_ms:durationSeconds*1000,counts:runStats,cost,summary_reference:summaryReference});}
export function summaryEvidenceFields(evidence:any){return{manifest_fingerprint:evidence.manifest.fingerprint,terminal_closure_reference:'terminal-closure.json',archive_manifest_reference:'archive-manifest.json',observability_completeness:evidence.closure.observability};}
export { publishArtifact };
