#!/usr/bin/env node
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

function args(argv=process.argv.slice(2)){const out:any={command:'verify'};for(let i=0;i<argv.length;i++){const value=argv[i];if(value==='verify'||value==='export'||value==='replay')out.command=value;else if(value.startsWith('--'))out[value.slice(2).replaceAll('-','_')]=argv[++i];}return out;}
function sha(bytes:Buffer|string){return crypto.createHash('sha256').update(bytes).digest('hex');}
function json(file:string){return JSON.parse(fs.readFileSync(file,'utf8'));}
function jsonl(file:string){return fs.existsSync(file)?fs.readFileSync(file,'utf8').trim().split('\n').filter(Boolean).map((line,index)=>{try{return JSON.parse(line);}catch{throw new Error(`${file}:${index+1}: invalid JSON`);}}):[];}
function required(file:string,errors:string[]){if(!fs.existsSync(file))errors.push(`missing ${file}`);return fs.existsSync(file);}
function safeRelative(root:string,reference:string){const target=path.resolve(root,reference);if(target!==path.resolve(root)&&!target.startsWith(`${path.resolve(root)}${path.sep}`))throw new Error(`unsafe bundle reference: ${reference}`);return target;}
function verifyRun(runDir:string){const errors:string[]=[];const requiredFiles=['run-manifest.json','terminal-closure.json','archive-manifest.json','producer-health.json','artifacts.jsonl','lifecycle/canonical-events.jsonl','lifecycle/read-models.json','pipeline.jsonl'];for(const file of requiredFiles)required(path.join(runDir,file),errors);if(errors.length)return{ok:false,errors};const manifest=json(path.join(runDir,'run-manifest.json'));const closure=json(path.join(runDir,'terminal-closure.json'));const archive=json(path.join(runDir,'archive-manifest.json'));const health=json(path.join(runDir,'producer-health.json'));if(manifest.fingerprint!==closure.manifest_fingerprint)errors.push('manifest fingerprint differs from terminal closure');if(!['complete','partial','degraded','unknown'].includes(closure.observability))errors.push('invalid observability completeness');for(const source of archive.sources??[]){const file=safeRelative(runDir,source.reference);if(!fs.existsSync(file))errors.push(`archive source missing: ${source.reference}`);else{const bytes=fs.readFileSync(file);if(bytes.length!==source.byte_length||sha(bytes)!==source.sha256)errors.push(`archive source corrupt: ${source.reference}`);}}for(const item of jsonl(path.join(runDir,'artifacts.jsonl'))){const file=safeRelative(runDir,item.reference);if(!fs.existsSync(file))errors.push(`artifact missing: ${item.artifact_id}`);else{const bytes=fs.readFileSync(file);if(bytes.length!==item.byte_length||sha(bytes)!==item.sha256)errors.push(`artifact corrupt: ${item.artifact_id}`);}}const lifecycle=jsonl(path.join(runDir,'lifecycle','canonical-events.jsonl'));if(archive.lifecycle?.event_count!==lifecycle.length)errors.push('lifecycle event count drift');if(!Array.isArray(health.producers)||!health.producers.length)errors.push('producer health is empty');return{ok:errors.length===0,errors,run_id:archive.run_id,contracts_checked:14,events:lifecycle.length,artifacts:jsonl(path.join(runDir,'artifacts.jsonl')).length};}
function copyBundle(runDir:string,output:string,contractsDir:string){const check=verifyRun(runDir);if(!check.ok)throw new Error(`source run is not exportable: ${check.errors.join('; ')}`);if(fs.existsSync(output))throw new Error(`output already exists: ${output}`);fs.cpSync(runDir,output,{recursive:true,errorOnExist:true});if(!fs.existsSync(contractsDir))throw new Error(`contracts directory missing: ${contractsDir}`);fs.cpSync(contractsDir,path.join(output,'contracts','telemetry','v1'),{recursive:true});fs.writeFileSync(path.join(output,'bundle-export.json'),`${JSON.stringify({schema_version:'pipeline_evidence_export.v1',exported_at:new Date().toISOString(),source_run_id:check.run_id,verification:check,contracts_reference:'contracts/telemetry/v1'},null,2)}\n`);return{...verifyRun(output),contracts:true};}
function replay(runDir:string){const check=verifyRun(runDir);if(!check.ok)return check;const lifecycle=jsonl(path.join(runDir,'lifecycle','canonical-events.jsonl'));const projection:any={pipeline:null,modules:{},gates:{}};for(const event of lifecycle){const target=event.module_id?['modules',event.module_id]:event.gate_id?['gates',event.gate_id]:['pipeline',null];const state=event.new_state??event.status??event.terminal_status??null;if(target[0]==='pipeline')projection.pipeline=state;else projection[target[0]][target[1]]=state;}const expected=json(path.join(runDir,'lifecycle','read-models.json'));const mismatches=[];const expectedPipeline=expected.pipeline?.status??expected.pipeline??null;if(projection.pipeline!==expectedPipeline)mismatches.push({target:'pipeline',expected:expectedPipeline,actual:projection.pipeline});for(const kind of ['modules','gates'])for(const [id,state] of Object.entries(projection[kind])){const expectedState=expected[kind]?.[id]?.status??null;if(state!==expectedState)mismatches.push({target:`${kind}/${id}`,expected:expectedState,actual:state});}return{...check,ok:check.ok&&mismatches.length===0,replay:{projection,mismatches,expected_sha256:sha(JSON.stringify(expected)),event_count:lifecycle.length}};}
const options=args();const runDir=path.resolve(options.run_dir??'');if(!options.run_dir)throw new Error('--run-dir is required');let result;if(options.command==='export'){if(!options.output)throw new Error('--output is required');result=copyBundle(runDir,path.resolve(options.output),path.resolve(options.contracts_dir??'contracts/telemetry/v1'));}else if(options.command==='replay')result=replay(runDir);else result=verifyRun(runDir);process.stdout.write(`${JSON.stringify(result,null,2)}\n`);if(!result.ok)process.exitCode=1;
