// Explicit remote/source terminal contract vectors, never native provider execution proof.
import crypto from 'node:crypto';
import {sha256Text} from '@kubeclaw/plugin-sdk';
import {createRemotePlanJob} from '../../../core/test-gates/remote-dispatch.ts';
import {attemptResultDigest,nodeResultDigest,remotePlanDigest,remotePlanResultDigest,remotePlanResultReceipt,resolvedTestPlanDigest,attestSourceSnapshot,gateCoverageDigest,stableTestIdentity} from '@kubeclaw/pipeline-test-gate-contract';
export function demoImportVectors(registry:any,bundle:any){
 const runId=bundle.invocation.runId,planId=bundle.invocation.planId;
 const modules=[{moduleId:'app',ownedPaths:['src'],requirements:[{id:'demo-auth',statement:'Demo authenticated workspace is usable'}]}];
 const policyBase={schemaVersion:'gate-coverage.v1',projectId:'demo',kind:'cumulative',baseRevision:'a'.repeat(40),modules,integrationRequirements:[],requiredChecks:[{checkId:'auth',requirementRefs:[{moduleId:'app',requirementId:'demo-auth'}],nodeIds:['auth']}]};
 const policy={...policyBase,policyDigest:gateCoverageDigest(policyBase as any)};
 const nodes=[['build','kubeclaw.container-build@1'],['manifest','kubeclaw.direct-command@1'],['deployment','kubeclaw.kubernetes-fixture@1'],['exposure','kubeclaw.tailscale-exposure@1'],['auth','kubeclaw.demo-auth-smoke@1']].map(([id,contract])=>{
  const entry=registry.testProviderContracts.get(contract);const registration=entry.registration;
  return {id,executionId:`execution:${id}`,testIdentity:stableTestIdentity({project:"demo",moduleId:null,gateId:"final-test",suiteInstanceId:null,nodeId:id,variation:{}}),suiteInstanceId:null,kind:registration.kind,provider:{...registration.package,registrationId:registration.registrationId,contractId:contract},reportAdapters:[],mode:registration.kind==='test'?'blocking':null,
   configuration:{schemaVersion:'provider-configuration.v1',contractId:contract,schemaDigest:entry.configSchemaDigest,values:id==='auth'?bundle.invocation.configuration.values:id==='exposure'?{retentionMode:'await-readiness'}:{}},dependencies:['build','manifest'].includes(id)?[]:(id==='deployment'?['build','manifest']:id==='auth'?['deployment','exposure']:['deployment']).map(nodeId=>({nodeId,acceptedResults:['passed']})),timeoutMs:3000,limits:{cpuMillis:1000,memoryBytes:67108864,logBytes:65536,artifactBytes:65536,artifactFiles:1,processes:1},retryCount:0,concurrencyGroup:null,parentNodeId:null,variation:{},evidence:{onPass:[],onFail:[],onError:[]},skipReason:null};
 });
 const link=(from:string,output:string,to:string,input:string,schemaId:string)=>({schemaVersion:'typed-link.v1',kind:'value',from:{nodeId:from,output},to:{nodeId:to,input},schemaId});
 const unsigned:any={schemaVersion:'resolved-test-plan.v1',planId,runId,project:'demo',scope:{moduleId:null,gateId:'final-test'},registrySnapshotDigest:registry.snapshotDigest,createdAt:new Date().toISOString(),suites:[],nodes,
  coverage:{policy,excludedNodeIds:[]},links:[link('build','image','deployment','image','kubeclaw.container-image@1'),{schemaVersion:'typed-link.v1',kind:'artifact',from:{nodeId:'manifest',output:'artifact-1'},to:{nodeId:'deployment',input:'checked-manifest'},mediaType:'application/vnd.kubeclaw.checked-kubernetes-yaml'},link('deployment','deployment','auth','deployment','kubeclaw.kubernetes-deployment-fixture@1'),link('deployment','demo-credentials','auth','credentials','kubeclaw.generated-demo-credentials@1'),link('exposure','exposure','auth','exposure','kubeclaw.public-endpoint-fixture@1'),link('deployment','deployment','exposure','deployment','kubeclaw.kubernetes-deployment-fixture@1')],concurrencyLimits:{default:1}};
 const plan={...unsigned,planDigest:resolvedTestPlanDigest(unsigned)};
 const archive=Buffer.from('explicit source envelope contract vector');
 const key=crypto.generateKeyPairSync('ed25519').privateKey.export({type:'pkcs8',format:'pem'});
 const sourceSnapshot=attestSourceSnapshot({schemaVersion:'source-snapshot.v1',sourceType:'git-commit',pipelineStageId:'final-test',repositoryId:'contract:repository',revision:`git:${'a'.repeat(40)}`,tree:`git:${'b'.repeat(40)}`,archiveContentDigest:sha256Text(archive.toString()),archiveSizeBytes:archive.length,creatorAuthority:'test:envelope'},key);
 const job=createRemotePlanJob({idempotencyKey:'demo:contract',pipelineStageId:'final-test',plan,sourceSnapshot,repositoryArchive:archive,grants:new Map(nodes.map(node=>[node.id,[]])),maximumConcurrency:1,submittedAt:new Date().toISOString()});
 const outputs=bundle.invocation.inputs;
 const get=(name:string)=>outputs.find((item:any)=>item.name===name).value;
 const authority=(digest:string,id:string)=>({receiptId:id,receiptDigest:remotePlanDigest({authorityId:`test-runner:${plan.planDigest}`,receiptId:id,resultDigest:digest})});
 const attempts=nodes.map(node=>{
  const base:any={schemaVersion:'attempt-result.v1',planId,runId,moduleId:null,gateId:'final-test',suiteInstanceId:null,nodeId:node.id,executionId:node.executionId,testIdentity:node.testIdentity,nodeKind:node.kind,
   attemptId:node.id==='auth'?bundle.invocation.attemptId:`attempt:${node.id}`,attemptNumber:1,provider:node.provider,mode:node.mode,executionState:'completed',outcome:'passed',startedAt:new Date(Date.now()-10000).toISOString(),completedAt:new Date().toISOString(),durationMs:1,summary:'Explicit terminal contract vector',counts:node.id==='auth'?bundle.result.counts:{total:1,passed:1,failed:0,skipped:0},findings:[],metrics:[],reports:[],evidence:[],resources:{logBytes:0,artifactBytes:0},exitCode:0,signal:null,providerDetails:null,
   outputs:node.id==='build'?[{name:'image',kind:'value',schemaId:'kubeclaw.container-image@1',value:{schemaVersion:'container-image.v1',reference:get('deployment').immutableImage,digest:get('deployment').immutableImage.split('@')[1]}}]:node.id==='manifest'?[{name:'artifact-1',kind:'artifact',artifact:{artifactId:'manifest:contract',type:'artifact',mediaType:'application/vnd.kubeclaw.checked-kubernetes-yaml',contentDigest:get('deployment').manifestDigest,sizeBytes:Buffer.byteLength('local application manifest contract vector'),storageUrl:'artifact://contract/manifest'}}]:node.id==='auth'?bundle.result.outputs:node.id==='deployment'?[{name:'deployment',kind:'value',schemaId:'kubeclaw.kubernetes-deployment-fixture@1',value:get('deployment')},{name:'demo-credentials',kind:'value',schemaId:'kubeclaw.generated-demo-credentials@1',value:get('credentials')}]:[{name:'exposure',kind:'value',schemaId:'kubeclaw.public-endpoint-fixture@1',value:get('exposure')}]};
  const resultDigest=attemptResultDigest(base);return {...base,resultDigest,receipt:authority(resultDigest,`receipt:${node.id}`)};
 });
 const results=nodes.map((node,index)=>{const base:any={schemaVersion:'node-result.v1',planId,runId,moduleId:null,gateId:'final-test',suiteInstanceId:null,nodeId:node.id,executionId:node.executionId,testIdentity:node.testIdentity,nodeKind:node.kind,mode:node.mode,state:'completed',outcome:'passed',attemptIds:[attempts[index].attemptId],finalAttemptId:attempts[index].attemptId,unstable:false,skipReason:null};const resultDigest=nodeResultDigest(base);return {...base,resultDigest,receipt:authority(resultDigest,`node:${node.id}`)};});
 const resultBase:any={schemaVersion:'buster-plan-result.v1',workerRevision:'c'.repeat(40),jobId:job.jobId,planId,planDigest:plan.planDigest,runId,attempts,nodes:results,cleanupErrors:[],completedAt:new Date().toISOString()};
 const resultDigest=remotePlanResultDigest(resultBase);const result={...resultBase,resultDigest,receipt:remotePlanResultReceipt(job.jobId,resultDigest)};
 const bytes=JSON.stringify(result);const status:any={schemaVersion:'buster-plan-status.v1',jobId:job.jobId,requestDigest:job.requestDigest,state:'completed',submittedAt:job.submittedAt,updatedAt:result.completedAt,result:{schemaVersion:'buster-plan-result-ref.v1',resultDigest,contentDigest:sha256Text(bytes),sizeBytes:Buffer.byteLength(bytes)},error:null};
 return {job,result,status,policy};
}
