// prompts/review.ts — Reviewer prompt builder

import { relPath, projectSrcPath } from '../core/paths.ts';
import { makePromptResult } from './shared.ts';

export function buildReviewerPrompt(config: any, gateId: any, gate: any, reviewer: any, instructions: any, lintBlock: any, relOutput: any) {
  const prompt = [
    '## Review Context',
    '',
    `**Project:** ${config.project}`,
    `**Project Source:** \`${relPath(config, projectSrcPath(config))}\``,
    `**Repo Root:** \`${config.repo_root}\``,
    `**Gate:** ${gateId} — ${gate.title}`,
    '',
    '---',
    '',
    instructions,
    '',
    '---',
    '',
    lintBlock,
    '## YOUR OUTPUT FILE',
    '',
    `You are reviewer: **${reviewer.label}** (model: ${reviewer.model})`,
    `Write your review JSON to: \`${relOutput}\``,
    '',
    'Your output file MUST contain raw, directly parseable JSON only. Do not wrap it in Markdown, do not use fenced code blocks, and do not write explanatory text outside the JSON object.',
    'The file content must be one JSON object with exactly this shape:',
    '{',
    '  "status": "PASS",',
    '  "critical_issues": [',
    '    {',
    '      "source": "tsc | eslint | architectural | ...",',
    '      "description": "what is wrong",',
    '      "affected_files": ["path/to/file.ts"],',
    '      "recommended_fix": "how to fix it"',
    '    }',
    '  ],',
    '  "deferred_issues": [],',
    '  "checked_contracts": ["path or contract ref that you actually opened"],',
    '  "opened_artifacts": ["path to verdict/log/artifact that you actually opened"],',
    '  "failed_commands": [],',
    '  "unverified_requirements": [],',
    '  "summary": "brief overall assessment"',
    '}',
    'Use `critical_issues: []` and `deferred_issues: []` when there are no issues in that category.',
    'Use `failed_commands: []` and `unverified_requirements: []` only when every required evidence command succeeded and every required requirement was verified.',
    '',
    'Rules:',
    '- Status is PASS only if there are zero critical issues.',
    '- Status is PASS only if `checked_contracts` and `opened_artifacts` are non-empty arrays.',
    '- Status is PASS only if `failed_commands` and `unverified_requirements` are empty arrays.',
    '- If a required evidence command fails, record it in `failed_commands` and return FAIL.',
    '- If a required contract or artifact cannot be opened, record it in `unverified_requirements` and return FAIL.',
    '- Architectural patterns that will propagate to downstream modules are ALWAYS critical, even if the current code works. Fix the pattern now while only 1-2 modules exist, not after 10+.',
    '- On early review gates (first half of the pipeline): prefer FAIL when in doubt. Foundation patterns are cheap to fix now, expensive to fix later.',
    '- Error response shapes, data model conventions, and API contract patterns that downstream modules will copy are critical by definition.',
    '- Lint findings that are errors (🔴) should be treated as critical unless they are false positives.',
    '- Lint warnings (🟡) should be deferred unless they indicate a real problem.',
    '- Add architectural issues the tools cannot detect (race conditions, security, design flaws).',
    '- Before PASS, actively look for ownership leaks, weak or shallow tests, unverified assumptions, and missing expected run artifacts.',
    '- Treat tests that only prove a file exists, a command exits, or a shared image builds as weak unless they also assert the module-owned contract.',
  ].join('\n');

  return makePromptResult(prompt, { phase: 'review', moduleId: gateId, attempt: 1 });
}
