export const AGENT_OBSERVABILITY_TELEMETRY_MAPPINGS = Object.freeze([
    {
        ingress_type: 'openclaw.agent.ended',
        hook: 'agent_end',
        current_telemetry_type: 'agent.ended',
        future_telemetry_type: 'agent.ended',
        promoted_by_default: true,
        notes: 'First-class Phase 3 terminal agent runtime schema; final message bodies remain on raw streams.',
    },
    {
        ingress_type: 'openclaw.llm.input',
        hook: 'llm_input',
        current_telemetry_type: 'agent.llm.input.summary',
        future_telemetry_type: 'agent.llm.input.summary',
        promoted_by_default: false,
        notes: 'Summary schema exists, but full prompt/system/history content remains on the payload stream unless explicitly promoted.',
    },
    {
        ingress_type: 'openclaw.llm.output',
        hook: 'llm_output',
        current_telemetry_type: 'agent.llm.output.summary',
        future_telemetry_type: 'agent.llm.output.summary',
        promoted_by_default: false,
        notes: 'Summary schema exists, but full assistant/provider output remains on the payload stream unless explicitly promoted.',
    },
    {
        ingress_type: 'openclaw.subagent.spawning',
        hook: 'subagent_spawning',
        current_telemetry_type: 'agent.spawn.requested',
        future_telemetry_type: 'agent.spawn.requested',
        promoted_by_default: true,
        notes: 'First-class typed spawn-request telemetry; raw requester payload remains on the agent-observability control stream.',
    },
    {
        ingress_type: 'openclaw.subagent.spawned',
        hook: 'subagent_spawned',
        current_telemetry_type: 'agent.spawned',
        future_telemetry_type: 'agent.spawned',
        promoted_by_default: true,
        notes: 'Reuses existing agent.spawned when identity is schema-compatible.',
    },
    {
        ingress_type: 'openclaw.subagent.delivery_target',
        hook: 'subagent_delivery_target',
        current_telemetry_type: 'agent.delivery.target',
        future_telemetry_type: 'agent.delivery.target',
        promoted_by_default: true,
        notes: 'First-class typed delivery-target telemetry; raw requester routing metadata remains on the agent-observability control stream.',
    },
    {
        ingress_type: 'openclaw.subagent.ended',
        hook: 'subagent_ended',
        current_telemetry_type: 'agent.ended',
        future_telemetry_type: 'agent.ended',
        promoted_by_default: true,
        notes: 'Uses first-class agent.ended with agent_scope=subagent.',
    },
    {
        ingress_type: 'openclaw.tool.started',
        hook: 'before_tool_call',
        current_telemetry_type: 'agent.tool.started',
        future_telemetry_type: 'agent.tool.started',
        promoted_by_default: true,
        notes: 'First-class schema carries bounded params metadata; full params remain on the payload stream.',
    },
    {
        ingress_type: 'openclaw.tool.finished',
        hook: 'after_tool_call',
        current_telemetry_type: 'agent.tool.finished',
        future_telemetry_type: 'agent.tool.finished',
        promoted_by_default: true,
        notes: 'First-class schema carries bounded result/error metadata; full results remain on the payload stream.',
    },
    {
        ingress_type: 'openclaw.model.started',
        hook: 'model_call_started',
        current_telemetry_type: 'agent.model.started',
        future_telemetry_type: 'agent.model.started',
        promoted_by_default: true,
        notes: 'Provider/model metadata is safe for canonical telemetry without raw LLM payload promotion.',
    },
    {
        ingress_type: 'openclaw.model.ended',
        hook: 'model_call_ended',
        current_telemetry_type: 'agent.model.ended',
        future_telemetry_type: 'agent.model.ended',
        promoted_by_default: true,
        notes: 'Provider/model terminal metadata and usage summary are canonical; separate cost.update promotion remains future work.',
    },
    {
        ingress_type: 'openclaw.model.usage',
        hook: 'model_usage',
        current_telemetry_type: 'cost.update',
        future_telemetry_type: 'cost.update',
        promoted_by_default: true,
        notes: 'Native OpenClaw diagnostic usage/cost/context evidence supersedes Gateway cost snapshots once live validation is complete.',
    },
    {
        ingress_type: 'openclaw.session.started',
        hook: 'session_start',
        current_telemetry_type: 'agent.session.started',
        future_telemetry_type: 'agent.session.started',
        promoted_by_default: true,
        notes: 'First-class session lifecycle schema approved in Phase 3.',
    },
    {
        ingress_type: 'openclaw.session.ended',
        hook: 'session_end',
        current_telemetry_type: 'agent.session.ended',
        future_telemetry_type: 'agent.session.ended',
        promoted_by_default: true,
        notes: 'First-class session lifecycle schema approved in Phase 3.',
    },
]);
export function getAgentObservabilityTelemetryMapping(ingressType) {
    return AGENT_OBSERVABILITY_TELEMETRY_MAPPINGS.find((mapping) => mapping.ingress_type === ingressType) ?? null;
}
